// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: argeo/ardk-next/common/protos/ar_client_envelope.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Niantic.ARDK.AR.Protobuf {

  /// <summary>Holder for reflection information generated from argeo/ardk-next/common/protos/ar_client_envelope.proto</summary>
  public static partial class ArClientEnvelopeReflection {

    #region Descriptor
    /// <summary>File descriptor for argeo/ardk-next/common/protos/ar_client_envelope.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ArClientEnvelopeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjZhcmdlby9hcmRrLW5leHQvY29tbW9uL3Byb3Rvcy9hcl9jbGllbnRfZW52",
            "ZWxvcGUucHJvdG8SDW5hci50ZWxlbWV0cnkaNmFyZ2VvL2FyZGstbmV4dC9j",
            "b21tb24vcHJvdG9zL2FyX2NvbW1vbl9tZXRhZGF0YS5wcm90byLFAQoQQVJD",
            "bGllbnRFbnZlbG9wZRI7CglhZ2VfbGV2ZWwYASABKA4yKC5uYXIudGVsZW1l",
            "dHJ5LkFSQ2xpZW50RW52ZWxvcGUuQWdlTGV2ZWwSOwoSYXJfY29tbW9uX21l",
            "dGFkYXRhGAIgASgLMh8ubmFyLnRlbGVtZXRyeS5BUkNvbW1vbk1ldGFkYXRh",
            "IjcKCEFnZUxldmVsEgsKB1VOS05PV04QABIJCgVNSU5PUhABEggKBFRFRU4Q",
            "AhIJCgVBRFVMVBADQlYKIWNvbS5uaWFudGljcHJvamVjdC5hcmRrLnRlbGVt",
            "ZXRyeVoWbmlhbnRpYy9hcmRrL3RlbGVtZXRyeaoCGE5pYW50aWMuQVJESy5B",
            "Ui5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Niantic.ARDK.AR.Protobuf.ArCommonMetadataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope), global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Parser, new[]{ "AgeLevel", "ArCommonMetadata" }, null, new[]{ typeof(global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ARClientEnvelope : pb::IMessage<ARClientEnvelope> {
    private static readonly pb::MessageParser<ARClientEnvelope> _parser = new pb::MessageParser<ARClientEnvelope>(() => new ARClientEnvelope());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ARClientEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ArClientEnvelopeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ARClientEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ARClientEnvelope(ARClientEnvelope other) : this() {
      ageLevel_ = other.ageLevel_;
      ArCommonMetadata = other.arCommonMetadata_ != null ? other.ArCommonMetadata.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ARClientEnvelope Clone() {
      return new ARClientEnvelope(this);
    }

    /// <summary>Field number for the "age_level" field.</summary>
    public const int AgeLevelFieldNumber = 1;
    private global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel ageLevel_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel AgeLevel {
      get { return ageLevel_; }
      set {
        ageLevel_ = value;
      }
    }

    /// <summary>Field number for the "ar_common_metadata" field.</summary>
    public const int ArCommonMetadataFieldNumber = 2;
    private global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata arCommonMetadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata ArCommonMetadata {
      get { return arCommonMetadata_; }
      set {
        arCommonMetadata_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ARClientEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ARClientEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AgeLevel != other.AgeLevel) return false;
      if (!object.Equals(ArCommonMetadata, other.ArCommonMetadata)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AgeLevel != 0) hash ^= AgeLevel.GetHashCode();
      if (arCommonMetadata_ != null) hash ^= ArCommonMetadata.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AgeLevel != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AgeLevel);
      }
      if (arCommonMetadata_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ArCommonMetadata);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AgeLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AgeLevel);
      }
      if (arCommonMetadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArCommonMetadata);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ARClientEnvelope other) {
      if (other == null) {
        return;
      }
      if (other.AgeLevel != 0) {
        AgeLevel = other.AgeLevel;
      }
      if (other.arCommonMetadata_ != null) {
        if (arCommonMetadata_ == null) {
          arCommonMetadata_ = new global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata();
        }
        ArCommonMetadata.MergeFrom(other.ArCommonMetadata);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ageLevel_ = (global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel) input.ReadEnum();
            break;
          }
          case 18: {
            if (arCommonMetadata_ == null) {
              arCommonMetadata_ = new global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata();
            }
            input.ReadMessage(arCommonMetadata_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ARClientEnvelope message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      ///  Age level of the user.
      /// </summary>
      public enum AgeLevel {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("MINOR")] Minor = 1,
        [pbr::OriginalName("TEEN")] Teen = 2,
        [pbr::OriginalName("ADULT")] Adult = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
