// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: argeo/ardk-next/common/protos/ar_client_envelope.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Niantic.Protobuf;
using pbc = global::Niantic.Protobuf.Collections;
using pbr = global::Niantic.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Niantic.ARDK.AR.Protobuf {

  /// <summary>Holder for reflection information generated from argeo/ardk-next/common/protos/ar_client_envelope.proto</summary>
  public static partial class ArClientEnvelopeReflection {

    #region Descriptor
    /// <summary>File descriptor for argeo/ardk-next/common/protos/ar_client_envelope.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ArClientEnvelopeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjZhcmdlby9hcmRrLW5leHQvY29tbW9uL3Byb3Rvcy9hcl9jbGllbnRfZW52",
            "ZWxvcGUucHJvdG8SDW5hci50ZWxlbWV0cnkaNmFyZ2VvL2FyZGstbmV4dC9j",
            "b21tb24vcHJvdG9zL2FyX2NvbW1vbl9tZXRhZGF0YS5wcm90byLhAQoQQVJD",
            "bGllbnRFbnZlbG9wZRJFCglhZ2VfbGV2ZWwYASABKA4yKC5uYXIudGVsZW1l",
            "dHJ5LkFSQ2xpZW50RW52ZWxvcGUuQWdlTGV2ZWxSCGFnZUxldmVsEk0KEmFy",
            "X2NvbW1vbl9tZXRhZGF0YRgCIAEoCzIfLm5hci50ZWxlbWV0cnkuQVJDb21t",
            "b25NZXRhZGF0YVIQYXJDb21tb25NZXRhZGF0YSI3CghBZ2VMZXZlbBILCgdV",
            "TktOT1dOEAASCQoFTUlOT1IQARIICgRURUVOEAISCQoFQURVTFQQA0JWCiFj",
            "b20ubmlhbnRpY3Byb2plY3QuYXJkay50ZWxlbWV0cnlaFm5pYW50aWMvYXJk",
            "ay90ZWxlbWV0cnmqAhhOaWFudGljLkFSREsuQVIuUHJvdG9idWZiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Niantic.ARDK.AR.Protobuf.ArCommonMetadataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope), global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Parser, new[]{ "AgeLevel", "ArCommonMetadata" }, null, new[]{ typeof(global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ARClientEnvelope : pb::IMessage<ARClientEnvelope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ARClientEnvelope> _parser = new pb::MessageParser<ARClientEnvelope>(() => new ARClientEnvelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ARClientEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ArClientEnvelopeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ARClientEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ARClientEnvelope(ARClientEnvelope other) : this() {
      ageLevel_ = other.ageLevel_;
      arCommonMetadata_ = other.arCommonMetadata_ != null ? other.arCommonMetadata_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ARClientEnvelope Clone() {
      return new ARClientEnvelope(this);
    }

    /// <summary>Field number for the "age_level" field.</summary>
    public const int AgeLevelFieldNumber = 1;
    private global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel ageLevel_ = global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel AgeLevel {
      get { return ageLevel_; }
      set {
        ageLevel_ = value;
      }
    }

    /// <summary>Field number for the "ar_common_metadata" field.</summary>
    public const int ArCommonMetadataFieldNumber = 2;
    private global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata arCommonMetadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata ArCommonMetadata {
      get { return arCommonMetadata_; }
      set {
        arCommonMetadata_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ARClientEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ARClientEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AgeLevel != other.AgeLevel) return false;
      if (!object.Equals(ArCommonMetadata, other.ArCommonMetadata)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AgeLevel != global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel.Unknown) hash ^= AgeLevel.GetHashCode();
      if (arCommonMetadata_ != null) hash ^= ArCommonMetadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AgeLevel != global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AgeLevel);
      }
      if (arCommonMetadata_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ArCommonMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AgeLevel != global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AgeLevel);
      }
      if (arCommonMetadata_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ArCommonMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AgeLevel != global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AgeLevel);
      }
      if (arCommonMetadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArCommonMetadata);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ARClientEnvelope other) {
      if (other == null) {
        return;
      }
      if (other.AgeLevel != global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel.Unknown) {
        AgeLevel = other.AgeLevel;
      }
      if (other.arCommonMetadata_ != null) {
        if (arCommonMetadata_ == null) {
          ArCommonMetadata = new global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata();
        }
        ArCommonMetadata.MergeFrom(other.ArCommonMetadata);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AgeLevel = (global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel) input.ReadEnum();
            break;
          }
          case 18: {
            if (arCommonMetadata_ == null) {
              ArCommonMetadata = new global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata();
            }
            input.ReadMessage(ArCommonMetadata);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AgeLevel = (global::Niantic.ARDK.AR.Protobuf.ARClientEnvelope.Types.AgeLevel) input.ReadEnum();
            break;
          }
          case 18: {
            if (arCommonMetadata_ == null) {
              ArCommonMetadata = new global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata();
            }
            input.ReadMessage(ArCommonMetadata);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ARClientEnvelope message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum AgeLevel {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("MINOR")] Minor = 1,
        [pbr::OriginalName("TEEN")] Teen = 2,
        [pbr::OriginalName("ADULT")] Adult = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
