// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: argeo/ardk-next/common/protos/ardk_device_map.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Niantic.Protobuf;
using pbc = global::Niantic.Protobuf.Collections;
using pbr = global::Niantic.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Niantic.Lightship.AR.Protobuf {

  /// <summary>Holder for reflection information generated from argeo/ardk-next/common/protos/ardk_device_map.proto</summary>
  public static partial class ArdkDeviceMapReflection {

    #region Descriptor
    /// <summary>File descriptor for argeo/ardk-next/common/protos/ardk_device_map.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ArdkDeviceMapReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNhcmdlby9hcmRrLW5leHQvY29tbW9uL3Byb3Rvcy9hcmRrX2RldmljZV9t",
            "YXAucHJvdG8SDmFyZGsuZGV2aWNlbWFwIugCCg1EZXZpY2VNYXBOb2RlEhYK",
            "BnN1YklkMRgBIAEoBFIGc3ViSWQxEhYKBnN1YklkMhgCIAEoBFIGc3ViSWQy",
            "EkQKCWFsZ29yaXRobRgDIAEoDjImLmFyZGsuZGV2aWNlbWFwLkRldmljZU1h",
            "cHBpbmdBbGdvcml0aG1SCWFsZ29yaXRobRJJCg9tYXBOb2RlRGF0YVR5cGUY",
            "BCABKA4yHy5hcmRrLmRldmljZW1hcC5NYXBOb2RlRGF0YVR5cGVSD21hcE5v",
            "ZGVEYXRhVHlwZRIuChJtYXBEYXRhVHlwZVZlcnNpb24YBSABKA1SEm1hcERh",
            "dGFUeXBlVmVyc2lvbhIYCgdtYXBEYXRhGAYgASgMUgdtYXBEYXRhEiAKC2Nv",
            "bmZpZ3NKc29uGAcgASgJUgtjb25maWdzSnNvbhIqChBtYXBBbmNob3JQYXls",
            "b2FkGAggASgMUhBtYXBBbmNob3JQYXlsb2FkIp8BCgZHcmFwaHMSQwoNZ3Jh",
            "cGhEYXRhVHlwZRgBIAEoDjIdLmFyZGsuZGV2aWNlbWFwLkdyYXBoRGF0YVR5",
            "cGVSDWdyYXBoRGF0YVR5cGUSMgoUZ3JhcGhEYXRhVHlwZVZlcnNpb24YAiAB",
            "KA1SFGdyYXBoRGF0YVR5cGVWZXJzaW9uEhwKCWdyYXBoRGF0YRgDIAEoDFIJ",
            "Z3JhcGhEYXRhIqgBCglEZXZpY2VNYXASRQoOZGV2aWNlTWFwTm9kZXMYASAD",
            "KAsyHS5hcmRrLmRldmljZW1hcC5EZXZpY2VNYXBOb2RlUg5kZXZpY2VNYXBO",
            "b2RlcxIuCgZncmFwaHMYAiABKAsyFi5hcmRrLmRldmljZW1hcC5HcmFwaHNS",
            "BmdyYXBocxIkCg1hbmNob3JQYXlsb2FkGAMgASgMUg1hbmNob3JQYXlsb2Fk",
            "KiMKFkRldmljZU1hcHBpbmdBbGdvcml0aG0SCQoFU2xpY2sQACovCg9NYXBO",
            "b2RlRGF0YVR5cGUSBwoDT3JiEAASEwoPTGVhcm5lZEZlYXR1cmVzEAEqGQoN",
            "R3JhcGhEYXRhVHlwZRIICgRBcmRrEABCIKoCHU5pYW50aWMuTGlnaHRzaGlw",
            "LkFSLlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Niantic.Lightship.AR.Protobuf.DeviceMappingAlgorithm), typeof(global::Niantic.Lightship.AR.Protobuf.MapNodeDataType), typeof(global::Niantic.Lightship.AR.Protobuf.GraphDataType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.Lightship.AR.Protobuf.DeviceMapNode), global::Niantic.Lightship.AR.Protobuf.DeviceMapNode.Parser, new[]{ "SubId1", "SubId2", "Algorithm", "MapNodeDataType", "MapDataTypeVersion", "MapData", "ConfigsJson", "MapAnchorPayload" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.Lightship.AR.Protobuf.Graphs), global::Niantic.Lightship.AR.Protobuf.Graphs.Parser, new[]{ "GraphDataType", "GraphDataTypeVersion", "GraphData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.Lightship.AR.Protobuf.DeviceMap), global::Niantic.Lightship.AR.Protobuf.DeviceMap.Parser, new[]{ "DeviceMapNodes", "Graphs", "AnchorPayload" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum DeviceMappingAlgorithm {
    [pbr::OriginalName("Slick")] Slick = 0,
  }

  public enum MapNodeDataType {
    [pbr::OriginalName("Orb")] Orb = 0,
    [pbr::OriginalName("LearnedFeatures")] LearnedFeatures = 1,
  }

  public enum GraphDataType {
    [pbr::OriginalName("Ardk")] Ardk = 0,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DeviceMapNode : pb::IMessage<DeviceMapNode>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeviceMapNode> _parser = new pb::MessageParser<DeviceMapNode>(() => new DeviceMapNode());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeviceMapNode> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.Lightship.AR.Protobuf.ArdkDeviceMapReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceMapNode() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceMapNode(DeviceMapNode other) : this() {
      subId1_ = other.subId1_;
      subId2_ = other.subId2_;
      algorithm_ = other.algorithm_;
      mapNodeDataType_ = other.mapNodeDataType_;
      mapDataTypeVersion_ = other.mapDataTypeVersion_;
      mapData_ = other.mapData_;
      configsJson_ = other.configsJson_;
      mapAnchorPayload_ = other.mapAnchorPayload_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceMapNode Clone() {
      return new DeviceMapNode(this);
    }

    /// <summary>Field number for the "subId1" field.</summary>
    public const int SubId1FieldNumber = 1;
    private ulong subId1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SubId1 {
      get { return subId1_; }
      set {
        subId1_ = value;
      }
    }

    /// <summary>Field number for the "subId2" field.</summary>
    public const int SubId2FieldNumber = 2;
    private ulong subId2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SubId2 {
      get { return subId2_; }
      set {
        subId2_ = value;
      }
    }

    /// <summary>Field number for the "algorithm" field.</summary>
    public const int AlgorithmFieldNumber = 3;
    private global::Niantic.Lightship.AR.Protobuf.DeviceMappingAlgorithm algorithm_ = global::Niantic.Lightship.AR.Protobuf.DeviceMappingAlgorithm.Slick;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.Lightship.AR.Protobuf.DeviceMappingAlgorithm Algorithm {
      get { return algorithm_; }
      set {
        algorithm_ = value;
      }
    }

    /// <summary>Field number for the "mapNodeDataType" field.</summary>
    public const int MapNodeDataTypeFieldNumber = 4;
    private global::Niantic.Lightship.AR.Protobuf.MapNodeDataType mapNodeDataType_ = global::Niantic.Lightship.AR.Protobuf.MapNodeDataType.Orb;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.Lightship.AR.Protobuf.MapNodeDataType MapNodeDataType {
      get { return mapNodeDataType_; }
      set {
        mapNodeDataType_ = value;
      }
    }

    /// <summary>Field number for the "mapDataTypeVersion" field.</summary>
    public const int MapDataTypeVersionFieldNumber = 5;
    private uint mapDataTypeVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MapDataTypeVersion {
      get { return mapDataTypeVersion_; }
      set {
        mapDataTypeVersion_ = value;
      }
    }

    /// <summary>Field number for the "mapData" field.</summary>
    public const int MapDataFieldNumber = 6;
    private pb::ByteString mapData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString MapData {
      get { return mapData_; }
      set {
        mapData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "configsJson" field.</summary>
    public const int ConfigsJsonFieldNumber = 7;
    private string configsJson_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ConfigsJson {
      get { return configsJson_; }
      set {
        configsJson_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mapAnchorPayload" field.</summary>
    public const int MapAnchorPayloadFieldNumber = 8;
    private pb::ByteString mapAnchorPayload_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString MapAnchorPayload {
      get { return mapAnchorPayload_; }
      set {
        mapAnchorPayload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeviceMapNode);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeviceMapNode other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SubId1 != other.SubId1) return false;
      if (SubId2 != other.SubId2) return false;
      if (Algorithm != other.Algorithm) return false;
      if (MapNodeDataType != other.MapNodeDataType) return false;
      if (MapDataTypeVersion != other.MapDataTypeVersion) return false;
      if (MapData != other.MapData) return false;
      if (ConfigsJson != other.ConfigsJson) return false;
      if (MapAnchorPayload != other.MapAnchorPayload) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SubId1 != 0UL) hash ^= SubId1.GetHashCode();
      if (SubId2 != 0UL) hash ^= SubId2.GetHashCode();
      if (Algorithm != global::Niantic.Lightship.AR.Protobuf.DeviceMappingAlgorithm.Slick) hash ^= Algorithm.GetHashCode();
      if (MapNodeDataType != global::Niantic.Lightship.AR.Protobuf.MapNodeDataType.Orb) hash ^= MapNodeDataType.GetHashCode();
      if (MapDataTypeVersion != 0) hash ^= MapDataTypeVersion.GetHashCode();
      if (MapData.Length != 0) hash ^= MapData.GetHashCode();
      if (ConfigsJson.Length != 0) hash ^= ConfigsJson.GetHashCode();
      if (MapAnchorPayload.Length != 0) hash ^= MapAnchorPayload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SubId1 != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(SubId1);
      }
      if (SubId2 != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(SubId2);
      }
      if (Algorithm != global::Niantic.Lightship.AR.Protobuf.DeviceMappingAlgorithm.Slick) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Algorithm);
      }
      if (MapNodeDataType != global::Niantic.Lightship.AR.Protobuf.MapNodeDataType.Orb) {
        output.WriteRawTag(32);
        output.WriteEnum((int) MapNodeDataType);
      }
      if (MapDataTypeVersion != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(MapDataTypeVersion);
      }
      if (MapData.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(MapData);
      }
      if (ConfigsJson.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ConfigsJson);
      }
      if (MapAnchorPayload.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(MapAnchorPayload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SubId1 != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(SubId1);
      }
      if (SubId2 != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(SubId2);
      }
      if (Algorithm != global::Niantic.Lightship.AR.Protobuf.DeviceMappingAlgorithm.Slick) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Algorithm);
      }
      if (MapNodeDataType != global::Niantic.Lightship.AR.Protobuf.MapNodeDataType.Orb) {
        output.WriteRawTag(32);
        output.WriteEnum((int) MapNodeDataType);
      }
      if (MapDataTypeVersion != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(MapDataTypeVersion);
      }
      if (MapData.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(MapData);
      }
      if (ConfigsJson.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ConfigsJson);
      }
      if (MapAnchorPayload.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(MapAnchorPayload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SubId1 != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SubId1);
      }
      if (SubId2 != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SubId2);
      }
      if (Algorithm != global::Niantic.Lightship.AR.Protobuf.DeviceMappingAlgorithm.Slick) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Algorithm);
      }
      if (MapNodeDataType != global::Niantic.Lightship.AR.Protobuf.MapNodeDataType.Orb) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MapNodeDataType);
      }
      if (MapDataTypeVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MapDataTypeVersion);
      }
      if (MapData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(MapData);
      }
      if (ConfigsJson.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConfigsJson);
      }
      if (MapAnchorPayload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(MapAnchorPayload);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeviceMapNode other) {
      if (other == null) {
        return;
      }
      if (other.SubId1 != 0UL) {
        SubId1 = other.SubId1;
      }
      if (other.SubId2 != 0UL) {
        SubId2 = other.SubId2;
      }
      if (other.Algorithm != global::Niantic.Lightship.AR.Protobuf.DeviceMappingAlgorithm.Slick) {
        Algorithm = other.Algorithm;
      }
      if (other.MapNodeDataType != global::Niantic.Lightship.AR.Protobuf.MapNodeDataType.Orb) {
        MapNodeDataType = other.MapNodeDataType;
      }
      if (other.MapDataTypeVersion != 0) {
        MapDataTypeVersion = other.MapDataTypeVersion;
      }
      if (other.MapData.Length != 0) {
        MapData = other.MapData;
      }
      if (other.ConfigsJson.Length != 0) {
        ConfigsJson = other.ConfigsJson;
      }
      if (other.MapAnchorPayload.Length != 0) {
        MapAnchorPayload = other.MapAnchorPayload;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SubId1 = input.ReadUInt64();
            break;
          }
          case 16: {
            SubId2 = input.ReadUInt64();
            break;
          }
          case 24: {
            Algorithm = (global::Niantic.Lightship.AR.Protobuf.DeviceMappingAlgorithm) input.ReadEnum();
            break;
          }
          case 32: {
            MapNodeDataType = (global::Niantic.Lightship.AR.Protobuf.MapNodeDataType) input.ReadEnum();
            break;
          }
          case 40: {
            MapDataTypeVersion = input.ReadUInt32();
            break;
          }
          case 50: {
            MapData = input.ReadBytes();
            break;
          }
          case 58: {
            ConfigsJson = input.ReadString();
            break;
          }
          case 66: {
            MapAnchorPayload = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SubId1 = input.ReadUInt64();
            break;
          }
          case 16: {
            SubId2 = input.ReadUInt64();
            break;
          }
          case 24: {
            Algorithm = (global::Niantic.Lightship.AR.Protobuf.DeviceMappingAlgorithm) input.ReadEnum();
            break;
          }
          case 32: {
            MapNodeDataType = (global::Niantic.Lightship.AR.Protobuf.MapNodeDataType) input.ReadEnum();
            break;
          }
          case 40: {
            MapDataTypeVersion = input.ReadUInt32();
            break;
          }
          case 50: {
            MapData = input.ReadBytes();
            break;
          }
          case 58: {
            ConfigsJson = input.ReadString();
            break;
          }
          case 66: {
            MapAnchorPayload = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Graphs : pb::IMessage<Graphs>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Graphs> _parser = new pb::MessageParser<Graphs>(() => new Graphs());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Graphs> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.Lightship.AR.Protobuf.ArdkDeviceMapReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Graphs() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Graphs(Graphs other) : this() {
      graphDataType_ = other.graphDataType_;
      graphDataTypeVersion_ = other.graphDataTypeVersion_;
      graphData_ = other.graphData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Graphs Clone() {
      return new Graphs(this);
    }

    /// <summary>Field number for the "graphDataType" field.</summary>
    public const int GraphDataTypeFieldNumber = 1;
    private global::Niantic.Lightship.AR.Protobuf.GraphDataType graphDataType_ = global::Niantic.Lightship.AR.Protobuf.GraphDataType.Ardk;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.Lightship.AR.Protobuf.GraphDataType GraphDataType {
      get { return graphDataType_; }
      set {
        graphDataType_ = value;
      }
    }

    /// <summary>Field number for the "graphDataTypeVersion" field.</summary>
    public const int GraphDataTypeVersionFieldNumber = 2;
    private uint graphDataTypeVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GraphDataTypeVersion {
      get { return graphDataTypeVersion_; }
      set {
        graphDataTypeVersion_ = value;
      }
    }

    /// <summary>Field number for the "graphData" field.</summary>
    public const int GraphDataFieldNumber = 3;
    private pb::ByteString graphData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString GraphData {
      get { return graphData_; }
      set {
        graphData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Graphs);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Graphs other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GraphDataType != other.GraphDataType) return false;
      if (GraphDataTypeVersion != other.GraphDataTypeVersion) return false;
      if (GraphData != other.GraphData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GraphDataType != global::Niantic.Lightship.AR.Protobuf.GraphDataType.Ardk) hash ^= GraphDataType.GetHashCode();
      if (GraphDataTypeVersion != 0) hash ^= GraphDataTypeVersion.GetHashCode();
      if (GraphData.Length != 0) hash ^= GraphData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GraphDataType != global::Niantic.Lightship.AR.Protobuf.GraphDataType.Ardk) {
        output.WriteRawTag(8);
        output.WriteEnum((int) GraphDataType);
      }
      if (GraphDataTypeVersion != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(GraphDataTypeVersion);
      }
      if (GraphData.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(GraphData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GraphDataType != global::Niantic.Lightship.AR.Protobuf.GraphDataType.Ardk) {
        output.WriteRawTag(8);
        output.WriteEnum((int) GraphDataType);
      }
      if (GraphDataTypeVersion != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(GraphDataTypeVersion);
      }
      if (GraphData.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(GraphData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GraphDataType != global::Niantic.Lightship.AR.Protobuf.GraphDataType.Ardk) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GraphDataType);
      }
      if (GraphDataTypeVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GraphDataTypeVersion);
      }
      if (GraphData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(GraphData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Graphs other) {
      if (other == null) {
        return;
      }
      if (other.GraphDataType != global::Niantic.Lightship.AR.Protobuf.GraphDataType.Ardk) {
        GraphDataType = other.GraphDataType;
      }
      if (other.GraphDataTypeVersion != 0) {
        GraphDataTypeVersion = other.GraphDataTypeVersion;
      }
      if (other.GraphData.Length != 0) {
        GraphData = other.GraphData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GraphDataType = (global::Niantic.Lightship.AR.Protobuf.GraphDataType) input.ReadEnum();
            break;
          }
          case 16: {
            GraphDataTypeVersion = input.ReadUInt32();
            break;
          }
          case 26: {
            GraphData = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GraphDataType = (global::Niantic.Lightship.AR.Protobuf.GraphDataType) input.ReadEnum();
            break;
          }
          case 16: {
            GraphDataTypeVersion = input.ReadUInt32();
            break;
          }
          case 26: {
            GraphData = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DeviceMap : pb::IMessage<DeviceMap>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeviceMap> _parser = new pb::MessageParser<DeviceMap>(() => new DeviceMap());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeviceMap> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.Lightship.AR.Protobuf.ArdkDeviceMapReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceMap() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceMap(DeviceMap other) : this() {
      deviceMapNodes_ = other.deviceMapNodes_.Clone();
      graphs_ = other.graphs_ != null ? other.graphs_.Clone() : null;
      anchorPayload_ = other.anchorPayload_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceMap Clone() {
      return new DeviceMap(this);
    }

    /// <summary>Field number for the "deviceMapNodes" field.</summary>
    public const int DeviceMapNodesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Niantic.Lightship.AR.Protobuf.DeviceMapNode> _repeated_deviceMapNodes_codec
        = pb::FieldCodec.ForMessage(10, global::Niantic.Lightship.AR.Protobuf.DeviceMapNode.Parser);
    private readonly pbc::RepeatedField<global::Niantic.Lightship.AR.Protobuf.DeviceMapNode> deviceMapNodes_ = new pbc::RepeatedField<global::Niantic.Lightship.AR.Protobuf.DeviceMapNode>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Niantic.Lightship.AR.Protobuf.DeviceMapNode> DeviceMapNodes {
      get { return deviceMapNodes_; }
    }

    /// <summary>Field number for the "graphs" field.</summary>
    public const int GraphsFieldNumber = 2;
    private global::Niantic.Lightship.AR.Protobuf.Graphs graphs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.Lightship.AR.Protobuf.Graphs Graphs {
      get { return graphs_; }
      set {
        graphs_ = value;
      }
    }

    /// <summary>Field number for the "anchorPayload" field.</summary>
    public const int AnchorPayloadFieldNumber = 3;
    private pb::ByteString anchorPayload_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString AnchorPayload {
      get { return anchorPayload_; }
      set {
        anchorPayload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeviceMap);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeviceMap other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!deviceMapNodes_.Equals(other.deviceMapNodes_)) return false;
      if (!object.Equals(Graphs, other.Graphs)) return false;
      if (AnchorPayload != other.AnchorPayload) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= deviceMapNodes_.GetHashCode();
      if (graphs_ != null) hash ^= Graphs.GetHashCode();
      if (AnchorPayload.Length != 0) hash ^= AnchorPayload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      deviceMapNodes_.WriteTo(output, _repeated_deviceMapNodes_codec);
      if (graphs_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Graphs);
      }
      if (AnchorPayload.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(AnchorPayload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      deviceMapNodes_.WriteTo(ref output, _repeated_deviceMapNodes_codec);
      if (graphs_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Graphs);
      }
      if (AnchorPayload.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(AnchorPayload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += deviceMapNodes_.CalculateSize(_repeated_deviceMapNodes_codec);
      if (graphs_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Graphs);
      }
      if (AnchorPayload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(AnchorPayload);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeviceMap other) {
      if (other == null) {
        return;
      }
      deviceMapNodes_.Add(other.deviceMapNodes_);
      if (other.graphs_ != null) {
        if (graphs_ == null) {
          Graphs = new global::Niantic.Lightship.AR.Protobuf.Graphs();
        }
        Graphs.MergeFrom(other.Graphs);
      }
      if (other.AnchorPayload.Length != 0) {
        AnchorPayload = other.AnchorPayload;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            deviceMapNodes_.AddEntriesFrom(input, _repeated_deviceMapNodes_codec);
            break;
          }
          case 18: {
            if (graphs_ == null) {
              Graphs = new global::Niantic.Lightship.AR.Protobuf.Graphs();
            }
            input.ReadMessage(Graphs);
            break;
          }
          case 26: {
            AnchorPayload = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            deviceMapNodes_.AddEntriesFrom(ref input, _repeated_deviceMapNodes_codec);
            break;
          }
          case 18: {
            if (graphs_ == null) {
              Graphs = new global::Niantic.Lightship.AR.Protobuf.Graphs();
            }
            input.ReadMessage(Graphs);
            break;
          }
          case 26: {
            AnchorPayload = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
