// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: argeo/infinitam/protos/ManagedPoseData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Niantic.Protobuf;
using pbc = global::Niantic.Protobuf.Collections;
using pbr = global::Niantic.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ManagedPoses {

  /// <summary>Holder for reflection information generated from argeo/infinitam/protos/ManagedPoseData.proto</summary>
  public static partial class ManagedPoseDataReflection {

    #region Descriptor
    /// <summary>File descriptor for argeo/infinitam/protos/ManagedPoseData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ManagedPoseDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixhcmdlby9pbmZpbml0YW0vcHJvdG9zL01hbmFnZWRQb3NlRGF0YS5wcm90",
            "bxIMTWFuYWdlZFBvc2VzGg9NYXRoVHlwZXMucHJvdG8i1wEKEVBsYWNlbWVu",
            "dEFjY3VyYWN5Ei4KEmhvcml6b250YWxTRE1ldGVycxgBIAEoAlISaG9yaXpv",
            "bnRhbFNETWV0ZXJzEioKEHZlcnRpY2FsU0RNZXRlcnMYAiABKAJSEHZlcnRp",
            "Y2FsU0RNZXRlcnMSNAoVaG9yaXpvbnRhbEFuZ2xlU0RSYWRzGAMgASgCUhVo",
            "b3Jpem9udGFsQW5nbGVTRFJhZHMSMAoTdmVydGljYWxBbmdsZVNEUmFkcxgE",
            "IAEoAlITdmVydGljYWxBbmdsZVNEUmFkcyLtAQoPTm9kZUFzc29jaWF0aW9u",
            "Ei8KCmlkZW50aWZpZXIYASABKAsyDy5NYXRoVHlwZXMuVVVJRFIKaWRlbnRp",
            "ZmllchJCChFtYW5hZ2VkUG9zZVRvTm9kZRgCIAEoCzIULk1hdGhUeXBlcy5U",
            "cmFuc2Zvcm1SEW1hbmFnZWRQb3NlVG9Ob2RlEhYKBndlaWdodBgDIAEoAlIG",
            "d2VpZ2h0Ek0KEXBsYWNlbWVudEFjY3VyYWN5GAQgASgLMh8uTWFuYWdlZFBv",
            "c2VzLlBsYWNlbWVudEFjY3VyYWN5UhFwbGFjZW1lbnRBY2N1cmFjeSKQAgoO",
            "R2VvQXNzb2NpYXRpb24SMQoIcm90YXRpb24YASABKAsyFS5NYXRoVHlwZXMu",
            "UXVhdGVybmlvblIIcm90YXRpb24SKAoPbGF0aXR1ZGVEZWdyZWVzGAIgASgB",
            "Ug9sYXRpdHVkZURlZ3JlZXMSKgoQbG9uZ2l0dWRlRGVncmVlcxgDIAEoAVIQ",
            "bG9uZ2l0dWRlRGVncmVlcxImCg5hbHRpdHVkZU1ldHJlcxgEIAEoAVIOYWx0",
            "aXR1ZGVNZXRyZXMSTQoRcGxhY2VtZW50QWNjdXJhY3kYBSABKAsyHy5NYW5h",
            "Z2VkUG9zZXMuUGxhY2VtZW50QWNjdXJhY3lSEXBsYWNlbWVudEFjY3VyYWN5",
            "IuQCCg9NYW5hZ2VkUG9zZURhdGESLwoKaWRlbnRpZmllchgBIAEoCzIPLk1h",
            "dGhUeXBlcy5VVUlEUgppZGVudGlmaWVyEhgKB3ZlcnNpb24YAiABKA1SB3Zl",
            "cnNpb24SJgoOY3JlYXRpb25UaW1lTXMYAyABKARSDmNyZWF0aW9uVGltZU1z",
            "Ek0KEXBsYWNlbWVudEFjY3VyYWN5GAQgASgLMh8uTWFuYWdlZFBvc2VzLlBs",
            "YWNlbWVudEFjY3VyYWN5UhFwbGFjZW1lbnRBY2N1cmFjeRJJChBub2RlQXNz",
            "b2NpYXRpb25zGAUgAygLMh0uTWFuYWdlZFBvc2VzLk5vZGVBc3NvY2lhdGlv",
            "blIQbm9kZUFzc29jaWF0aW9ucxJECg5nZW9Bc3NvY2lhdGlvbhgGIAEoCzIc",
            "Lk1hbmFnZWRQb3Nlcy5HZW9Bc3NvY2lhdGlvblIOZ2VvQXNzb2NpYXRpb25C",
            "LQopY29tLm5pYW50aWNwcm9qZWN0LmFyZ2VvLmluZmluaXRhbS5wcm90b3NQ",
            "AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MathTypes.MathTypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ManagedPoses.PlacementAccuracy), global::ManagedPoses.PlacementAccuracy.Parser, new[]{ "HorizontalSDMeters", "VerticalSDMeters", "HorizontalAngleSDRads", "VerticalAngleSDRads" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ManagedPoses.NodeAssociation), global::ManagedPoses.NodeAssociation.Parser, new[]{ "Identifier", "ManagedPoseToNode", "Weight", "PlacementAccuracy" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ManagedPoses.GeoAssociation), global::ManagedPoses.GeoAssociation.Parser, new[]{ "Rotation", "LatitudeDegrees", "LongitudeDegrees", "AltitudeMetres", "PlacementAccuracy" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ManagedPoses.ManagedPoseData), global::ManagedPoses.ManagedPoseData.Parser, new[]{ "Identifier", "Version", "CreationTimeMs", "PlacementAccuracy", "NodeAssociations", "GeoAssociation" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlacementAccuracy : pb::IMessage<PlacementAccuracy>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlacementAccuracy> _parser = new pb::MessageParser<PlacementAccuracy>(() => new PlacementAccuracy());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlacementAccuracy> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManagedPoses.ManagedPoseDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlacementAccuracy() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlacementAccuracy(PlacementAccuracy other) : this() {
      horizontalSDMeters_ = other.horizontalSDMeters_;
      verticalSDMeters_ = other.verticalSDMeters_;
      horizontalAngleSDRads_ = other.horizontalAngleSDRads_;
      verticalAngleSDRads_ = other.verticalAngleSDRads_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlacementAccuracy Clone() {
      return new PlacementAccuracy(this);
    }

    /// <summary>Field number for the "horizontalSDMeters" field.</summary>
    public const int HorizontalSDMetersFieldNumber = 1;
    private float horizontalSDMeters_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float HorizontalSDMeters {
      get { return horizontalSDMeters_; }
      set {
        horizontalSDMeters_ = value;
      }
    }

    /// <summary>Field number for the "verticalSDMeters" field.</summary>
    public const int VerticalSDMetersFieldNumber = 2;
    private float verticalSDMeters_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VerticalSDMeters {
      get { return verticalSDMeters_; }
      set {
        verticalSDMeters_ = value;
      }
    }

    /// <summary>Field number for the "horizontalAngleSDRads" field.</summary>
    public const int HorizontalAngleSDRadsFieldNumber = 3;
    private float horizontalAngleSDRads_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float HorizontalAngleSDRads {
      get { return horizontalAngleSDRads_; }
      set {
        horizontalAngleSDRads_ = value;
      }
    }

    /// <summary>Field number for the "verticalAngleSDRads" field.</summary>
    public const int VerticalAngleSDRadsFieldNumber = 4;
    private float verticalAngleSDRads_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VerticalAngleSDRads {
      get { return verticalAngleSDRads_; }
      set {
        verticalAngleSDRads_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlacementAccuracy);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlacementAccuracy other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(HorizontalSDMeters, other.HorizontalSDMeters)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VerticalSDMeters, other.VerticalSDMeters)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(HorizontalAngleSDRads, other.HorizontalAngleSDRads)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VerticalAngleSDRads, other.VerticalAngleSDRads)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HorizontalSDMeters != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(HorizontalSDMeters);
      if (VerticalSDMeters != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VerticalSDMeters);
      if (HorizontalAngleSDRads != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(HorizontalAngleSDRads);
      if (VerticalAngleSDRads != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VerticalAngleSDRads);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HorizontalSDMeters != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(HorizontalSDMeters);
      }
      if (VerticalSDMeters != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(VerticalSDMeters);
      }
      if (HorizontalAngleSDRads != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(HorizontalAngleSDRads);
      }
      if (VerticalAngleSDRads != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(VerticalAngleSDRads);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HorizontalSDMeters != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(HorizontalSDMeters);
      }
      if (VerticalSDMeters != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(VerticalSDMeters);
      }
      if (HorizontalAngleSDRads != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(HorizontalAngleSDRads);
      }
      if (VerticalAngleSDRads != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(VerticalAngleSDRads);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HorizontalSDMeters != 0F) {
        size += 1 + 4;
      }
      if (VerticalSDMeters != 0F) {
        size += 1 + 4;
      }
      if (HorizontalAngleSDRads != 0F) {
        size += 1 + 4;
      }
      if (VerticalAngleSDRads != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlacementAccuracy other) {
      if (other == null) {
        return;
      }
      if (other.HorizontalSDMeters != 0F) {
        HorizontalSDMeters = other.HorizontalSDMeters;
      }
      if (other.VerticalSDMeters != 0F) {
        VerticalSDMeters = other.VerticalSDMeters;
      }
      if (other.HorizontalAngleSDRads != 0F) {
        HorizontalAngleSDRads = other.HorizontalAngleSDRads;
      }
      if (other.VerticalAngleSDRads != 0F) {
        VerticalAngleSDRads = other.VerticalAngleSDRads;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            HorizontalSDMeters = input.ReadFloat();
            break;
          }
          case 21: {
            VerticalSDMeters = input.ReadFloat();
            break;
          }
          case 29: {
            HorizontalAngleSDRads = input.ReadFloat();
            break;
          }
          case 37: {
            VerticalAngleSDRads = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            HorizontalSDMeters = input.ReadFloat();
            break;
          }
          case 21: {
            VerticalSDMeters = input.ReadFloat();
            break;
          }
          case 29: {
            HorizontalAngleSDRads = input.ReadFloat();
            break;
          }
          case 37: {
            VerticalAngleSDRads = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NodeAssociation : pb::IMessage<NodeAssociation>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NodeAssociation> _parser = new pb::MessageParser<NodeAssociation>(() => new NodeAssociation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NodeAssociation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManagedPoses.ManagedPoseDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NodeAssociation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NodeAssociation(NodeAssociation other) : this() {
      identifier_ = other.identifier_ != null ? other.identifier_.Clone() : null;
      managedPoseToNode_ = other.managedPoseToNode_ != null ? other.managedPoseToNode_.Clone() : null;
      weight_ = other.weight_;
      placementAccuracy_ = other.placementAccuracy_ != null ? other.placementAccuracy_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NodeAssociation Clone() {
      return new NodeAssociation(this);
    }

    /// <summary>Field number for the "identifier" field.</summary>
    public const int IdentifierFieldNumber = 1;
    private global::MathTypes.UUID identifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MathTypes.UUID Identifier {
      get { return identifier_; }
      set {
        identifier_ = value;
      }
    }

    /// <summary>Field number for the "managedPoseToNode" field.</summary>
    public const int ManagedPoseToNodeFieldNumber = 2;
    private global::MathTypes.Transform managedPoseToNode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MathTypes.Transform ManagedPoseToNode {
      get { return managedPoseToNode_; }
      set {
        managedPoseToNode_ = value;
      }
    }

    /// <summary>Field number for the "weight" field.</summary>
    public const int WeightFieldNumber = 3;
    private float weight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Weight {
      get { return weight_; }
      set {
        weight_ = value;
      }
    }

    /// <summary>Field number for the "placementAccuracy" field.</summary>
    public const int PlacementAccuracyFieldNumber = 4;
    private global::ManagedPoses.PlacementAccuracy placementAccuracy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManagedPoses.PlacementAccuracy PlacementAccuracy {
      get { return placementAccuracy_; }
      set {
        placementAccuracy_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NodeAssociation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NodeAssociation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Identifier, other.Identifier)) return false;
      if (!object.Equals(ManagedPoseToNode, other.ManagedPoseToNode)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Weight, other.Weight)) return false;
      if (!object.Equals(PlacementAccuracy, other.PlacementAccuracy)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (identifier_ != null) hash ^= Identifier.GetHashCode();
      if (managedPoseToNode_ != null) hash ^= ManagedPoseToNode.GetHashCode();
      if (Weight != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Weight);
      if (placementAccuracy_ != null) hash ^= PlacementAccuracy.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (identifier_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Identifier);
      }
      if (managedPoseToNode_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ManagedPoseToNode);
      }
      if (Weight != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Weight);
      }
      if (placementAccuracy_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(PlacementAccuracy);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (identifier_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Identifier);
      }
      if (managedPoseToNode_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ManagedPoseToNode);
      }
      if (Weight != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Weight);
      }
      if (placementAccuracy_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(PlacementAccuracy);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (identifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Identifier);
      }
      if (managedPoseToNode_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ManagedPoseToNode);
      }
      if (Weight != 0F) {
        size += 1 + 4;
      }
      if (placementAccuracy_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlacementAccuracy);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NodeAssociation other) {
      if (other == null) {
        return;
      }
      if (other.identifier_ != null) {
        if (identifier_ == null) {
          Identifier = new global::MathTypes.UUID();
        }
        Identifier.MergeFrom(other.Identifier);
      }
      if (other.managedPoseToNode_ != null) {
        if (managedPoseToNode_ == null) {
          ManagedPoseToNode = new global::MathTypes.Transform();
        }
        ManagedPoseToNode.MergeFrom(other.ManagedPoseToNode);
      }
      if (other.Weight != 0F) {
        Weight = other.Weight;
      }
      if (other.placementAccuracy_ != null) {
        if (placementAccuracy_ == null) {
          PlacementAccuracy = new global::ManagedPoses.PlacementAccuracy();
        }
        PlacementAccuracy.MergeFrom(other.PlacementAccuracy);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (identifier_ == null) {
              Identifier = new global::MathTypes.UUID();
            }
            input.ReadMessage(Identifier);
            break;
          }
          case 18: {
            if (managedPoseToNode_ == null) {
              ManagedPoseToNode = new global::MathTypes.Transform();
            }
            input.ReadMessage(ManagedPoseToNode);
            break;
          }
          case 29: {
            Weight = input.ReadFloat();
            break;
          }
          case 34: {
            if (placementAccuracy_ == null) {
              PlacementAccuracy = new global::ManagedPoses.PlacementAccuracy();
            }
            input.ReadMessage(PlacementAccuracy);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (identifier_ == null) {
              Identifier = new global::MathTypes.UUID();
            }
            input.ReadMessage(Identifier);
            break;
          }
          case 18: {
            if (managedPoseToNode_ == null) {
              ManagedPoseToNode = new global::MathTypes.Transform();
            }
            input.ReadMessage(ManagedPoseToNode);
            break;
          }
          case 29: {
            Weight = input.ReadFloat();
            break;
          }
          case 34: {
            if (placementAccuracy_ == null) {
              PlacementAccuracy = new global::ManagedPoses.PlacementAccuracy();
            }
            input.ReadMessage(PlacementAccuracy);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GeoAssociation : pb::IMessage<GeoAssociation>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GeoAssociation> _parser = new pb::MessageParser<GeoAssociation>(() => new GeoAssociation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GeoAssociation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManagedPoses.ManagedPoseDataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GeoAssociation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GeoAssociation(GeoAssociation other) : this() {
      rotation_ = other.rotation_ != null ? other.rotation_.Clone() : null;
      latitudeDegrees_ = other.latitudeDegrees_;
      longitudeDegrees_ = other.longitudeDegrees_;
      altitudeMetres_ = other.altitudeMetres_;
      placementAccuracy_ = other.placementAccuracy_ != null ? other.placementAccuracy_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GeoAssociation Clone() {
      return new GeoAssociation(this);
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 1;
    private global::MathTypes.Quaternion rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MathTypes.Quaternion Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    /// <summary>Field number for the "latitudeDegrees" field.</summary>
    public const int LatitudeDegreesFieldNumber = 2;
    private double latitudeDegrees_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double LatitudeDegrees {
      get { return latitudeDegrees_; }
      set {
        latitudeDegrees_ = value;
      }
    }

    /// <summary>Field number for the "longitudeDegrees" field.</summary>
    public const int LongitudeDegreesFieldNumber = 3;
    private double longitudeDegrees_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double LongitudeDegrees {
      get { return longitudeDegrees_; }
      set {
        longitudeDegrees_ = value;
      }
    }

    /// <summary>Field number for the "altitudeMetres" field.</summary>
    public const int AltitudeMetresFieldNumber = 4;
    private double altitudeMetres_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double AltitudeMetres {
      get { return altitudeMetres_; }
      set {
        altitudeMetres_ = value;
      }
    }

    /// <summary>Field number for the "placementAccuracy" field.</summary>
    public const int PlacementAccuracyFieldNumber = 5;
    private global::ManagedPoses.PlacementAccuracy placementAccuracy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManagedPoses.PlacementAccuracy PlacementAccuracy {
      get { return placementAccuracy_; }
      set {
        placementAccuracy_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GeoAssociation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GeoAssociation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Rotation, other.Rotation)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LatitudeDegrees, other.LatitudeDegrees)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LongitudeDegrees, other.LongitudeDegrees)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(AltitudeMetres, other.AltitudeMetres)) return false;
      if (!object.Equals(PlacementAccuracy, other.PlacementAccuracy)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (rotation_ != null) hash ^= Rotation.GetHashCode();
      if (LatitudeDegrees != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LatitudeDegrees);
      if (LongitudeDegrees != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LongitudeDegrees);
      if (AltitudeMetres != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(AltitudeMetres);
      if (placementAccuracy_ != null) hash ^= PlacementAccuracy.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (rotation_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Rotation);
      }
      if (LatitudeDegrees != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(LatitudeDegrees);
      }
      if (LongitudeDegrees != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(LongitudeDegrees);
      }
      if (AltitudeMetres != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(AltitudeMetres);
      }
      if (placementAccuracy_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(PlacementAccuracy);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (rotation_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Rotation);
      }
      if (LatitudeDegrees != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(LatitudeDegrees);
      }
      if (LongitudeDegrees != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(LongitudeDegrees);
      }
      if (AltitudeMetres != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(AltitudeMetres);
      }
      if (placementAccuracy_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(PlacementAccuracy);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (rotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
      }
      if (LatitudeDegrees != 0D) {
        size += 1 + 8;
      }
      if (LongitudeDegrees != 0D) {
        size += 1 + 8;
      }
      if (AltitudeMetres != 0D) {
        size += 1 + 8;
      }
      if (placementAccuracy_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlacementAccuracy);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GeoAssociation other) {
      if (other == null) {
        return;
      }
      if (other.rotation_ != null) {
        if (rotation_ == null) {
          Rotation = new global::MathTypes.Quaternion();
        }
        Rotation.MergeFrom(other.Rotation);
      }
      if (other.LatitudeDegrees != 0D) {
        LatitudeDegrees = other.LatitudeDegrees;
      }
      if (other.LongitudeDegrees != 0D) {
        LongitudeDegrees = other.LongitudeDegrees;
      }
      if (other.AltitudeMetres != 0D) {
        AltitudeMetres = other.AltitudeMetres;
      }
      if (other.placementAccuracy_ != null) {
        if (placementAccuracy_ == null) {
          PlacementAccuracy = new global::ManagedPoses.PlacementAccuracy();
        }
        PlacementAccuracy.MergeFrom(other.PlacementAccuracy);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (rotation_ == null) {
              Rotation = new global::MathTypes.Quaternion();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 17: {
            LatitudeDegrees = input.ReadDouble();
            break;
          }
          case 25: {
            LongitudeDegrees = input.ReadDouble();
            break;
          }
          case 33: {
            AltitudeMetres = input.ReadDouble();
            break;
          }
          case 42: {
            if (placementAccuracy_ == null) {
              PlacementAccuracy = new global::ManagedPoses.PlacementAccuracy();
            }
            input.ReadMessage(PlacementAccuracy);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (rotation_ == null) {
              Rotation = new global::MathTypes.Quaternion();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 17: {
            LatitudeDegrees = input.ReadDouble();
            break;
          }
          case 25: {
            LongitudeDegrees = input.ReadDouble();
            break;
          }
          case 33: {
            AltitudeMetres = input.ReadDouble();
            break;
          }
          case 42: {
            if (placementAccuracy_ == null) {
              PlacementAccuracy = new global::ManagedPoses.PlacementAccuracy();
            }
            input.ReadMessage(PlacementAccuracy);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ManagedPoseData : pb::IMessage<ManagedPoseData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ManagedPoseData> _parser = new pb::MessageParser<ManagedPoseData>(() => new ManagedPoseData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ManagedPoseData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManagedPoses.ManagedPoseDataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ManagedPoseData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ManagedPoseData(ManagedPoseData other) : this() {
      identifier_ = other.identifier_ != null ? other.identifier_.Clone() : null;
      version_ = other.version_;
      creationTimeMs_ = other.creationTimeMs_;
      placementAccuracy_ = other.placementAccuracy_ != null ? other.placementAccuracy_.Clone() : null;
      nodeAssociations_ = other.nodeAssociations_.Clone();
      geoAssociation_ = other.geoAssociation_ != null ? other.geoAssociation_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ManagedPoseData Clone() {
      return new ManagedPoseData(this);
    }

    /// <summary>Field number for the "identifier" field.</summary>
    public const int IdentifierFieldNumber = 1;
    private global::MathTypes.UUID identifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MathTypes.UUID Identifier {
      get { return identifier_; }
      set {
        identifier_ = value;
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 2;
    private uint version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "creationTimeMs" field.</summary>
    public const int CreationTimeMsFieldNumber = 3;
    private ulong creationTimeMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CreationTimeMs {
      get { return creationTimeMs_; }
      set {
        creationTimeMs_ = value;
      }
    }

    /// <summary>Field number for the "placementAccuracy" field.</summary>
    public const int PlacementAccuracyFieldNumber = 4;
    private global::ManagedPoses.PlacementAccuracy placementAccuracy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManagedPoses.PlacementAccuracy PlacementAccuracy {
      get { return placementAccuracy_; }
      set {
        placementAccuracy_ = value;
      }
    }

    /// <summary>Field number for the "nodeAssociations" field.</summary>
    public const int NodeAssociationsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::ManagedPoses.NodeAssociation> _repeated_nodeAssociations_codec
        = pb::FieldCodec.ForMessage(42, global::ManagedPoses.NodeAssociation.Parser);
    private readonly pbc::RepeatedField<global::ManagedPoses.NodeAssociation> nodeAssociations_ = new pbc::RepeatedField<global::ManagedPoses.NodeAssociation>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ManagedPoses.NodeAssociation> NodeAssociations {
      get { return nodeAssociations_; }
    }

    /// <summary>Field number for the "geoAssociation" field.</summary>
    public const int GeoAssociationFieldNumber = 6;
    private global::ManagedPoses.GeoAssociation geoAssociation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManagedPoses.GeoAssociation GeoAssociation {
      get { return geoAssociation_; }
      set {
        geoAssociation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ManagedPoseData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ManagedPoseData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Identifier, other.Identifier)) return false;
      if (Version != other.Version) return false;
      if (CreationTimeMs != other.CreationTimeMs) return false;
      if (!object.Equals(PlacementAccuracy, other.PlacementAccuracy)) return false;
      if(!nodeAssociations_.Equals(other.nodeAssociations_)) return false;
      if (!object.Equals(GeoAssociation, other.GeoAssociation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (identifier_ != null) hash ^= Identifier.GetHashCode();
      if (Version != 0) hash ^= Version.GetHashCode();
      if (CreationTimeMs != 0UL) hash ^= CreationTimeMs.GetHashCode();
      if (placementAccuracy_ != null) hash ^= PlacementAccuracy.GetHashCode();
      hash ^= nodeAssociations_.GetHashCode();
      if (geoAssociation_ != null) hash ^= GeoAssociation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (identifier_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Identifier);
      }
      if (Version != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Version);
      }
      if (CreationTimeMs != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(CreationTimeMs);
      }
      if (placementAccuracy_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(PlacementAccuracy);
      }
      nodeAssociations_.WriteTo(output, _repeated_nodeAssociations_codec);
      if (geoAssociation_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(GeoAssociation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (identifier_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Identifier);
      }
      if (Version != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Version);
      }
      if (CreationTimeMs != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(CreationTimeMs);
      }
      if (placementAccuracy_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(PlacementAccuracy);
      }
      nodeAssociations_.WriteTo(ref output, _repeated_nodeAssociations_codec);
      if (geoAssociation_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(GeoAssociation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (identifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Identifier);
      }
      if (Version != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Version);
      }
      if (CreationTimeMs != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CreationTimeMs);
      }
      if (placementAccuracy_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlacementAccuracy);
      }
      size += nodeAssociations_.CalculateSize(_repeated_nodeAssociations_codec);
      if (geoAssociation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GeoAssociation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ManagedPoseData other) {
      if (other == null) {
        return;
      }
      if (other.identifier_ != null) {
        if (identifier_ == null) {
          Identifier = new global::MathTypes.UUID();
        }
        Identifier.MergeFrom(other.Identifier);
      }
      if (other.Version != 0) {
        Version = other.Version;
      }
      if (other.CreationTimeMs != 0UL) {
        CreationTimeMs = other.CreationTimeMs;
      }
      if (other.placementAccuracy_ != null) {
        if (placementAccuracy_ == null) {
          PlacementAccuracy = new global::ManagedPoses.PlacementAccuracy();
        }
        PlacementAccuracy.MergeFrom(other.PlacementAccuracy);
      }
      nodeAssociations_.Add(other.nodeAssociations_);
      if (other.geoAssociation_ != null) {
        if (geoAssociation_ == null) {
          GeoAssociation = new global::ManagedPoses.GeoAssociation();
        }
        GeoAssociation.MergeFrom(other.GeoAssociation);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (identifier_ == null) {
              Identifier = new global::MathTypes.UUID();
            }
            input.ReadMessage(Identifier);
            break;
          }
          case 16: {
            Version = input.ReadUInt32();
            break;
          }
          case 24: {
            CreationTimeMs = input.ReadUInt64();
            break;
          }
          case 34: {
            if (placementAccuracy_ == null) {
              PlacementAccuracy = new global::ManagedPoses.PlacementAccuracy();
            }
            input.ReadMessage(PlacementAccuracy);
            break;
          }
          case 42: {
            nodeAssociations_.AddEntriesFrom(input, _repeated_nodeAssociations_codec);
            break;
          }
          case 50: {
            if (geoAssociation_ == null) {
              GeoAssociation = new global::ManagedPoses.GeoAssociation();
            }
            input.ReadMessage(GeoAssociation);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (identifier_ == null) {
              Identifier = new global::MathTypes.UUID();
            }
            input.ReadMessage(Identifier);
            break;
          }
          case 16: {
            Version = input.ReadUInt32();
            break;
          }
          case 24: {
            CreationTimeMs = input.ReadUInt64();
            break;
          }
          case 34: {
            if (placementAccuracy_ == null) {
              PlacementAccuracy = new global::ManagedPoses.PlacementAccuracy();
            }
            input.ReadMessage(PlacementAccuracy);
            break;
          }
          case 42: {
            nodeAssociations_.AddEntriesFrom(ref input, _repeated_nodeAssociations_codec);
            break;
          }
          case 50: {
            if (geoAssociation_ == null) {
              GeoAssociation = new global::ManagedPoses.GeoAssociation();
            }
            input.ReadMessage(GeoAssociation);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
