// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: argeo/Scaniverse/ScanKit/ScanKit/Proto/ScanKitPublicProtos.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Niantic.ARDK.AR.Protobuf {

  /// <summary>Holder for reflection information generated from argeo/Scaniverse/ScanKit/ScanKit/Proto/ScanKitPublicProtos.proto</summary>
  public static partial class ScanKitPublicProtosReflection {

    #region Descriptor
    /// <summary>File descriptor for argeo/Scaniverse/ScanKit/ScanKit/Proto/ScanKitPublicProtos.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ScanKitPublicProtosReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkBhcmdlby9TY2FuaXZlcnNlL1NjYW5LaXQvU2NhbktpdC9Qcm90by9TY2Fu",
            "S2l0UHVibGljUHJvdG9zLnByb3RvIoEBCgtGcmFtZXNQcm90bxIKCgJpZBgB",
            "IAEoCRIbCgZmcmFtZXMYBSADKAsyCy5GcmFtZVByb3RvEiYKB2FuY2hvcnMY",
            "DSADKAsyFS5BZmZpbmVUcmFuc2Zvcm1Qcm90bxIhCglsb2NhdGlvbnMYAiAD",
            "KAsyDi5Mb2NhdGlvblByb3RvIvkBCgpGcmFtZVByb3RvEgoKAmlkGAEgASgF",
            "Eg4KBmFuY2hvchgCIAEoBRIRCgl0aW1lc3RhbXAYAyABKAESIgoGY2FtZXJh",
            "GAQgASgLMhIuQ2FtZXJhUGFyYW1zUHJvdG8SKAoJdHJhbnNmb3JtGAUgASgL",
            "MhUuQWZmaW5lVHJhbnNmb3JtUHJvdG8SJAoIZXhwb3N1cmUYBiABKAsyEi5F",
            "eHBvc3VyZUluZm9Qcm90bxIfCgVyYW5nZRgHIAEoCzIQLkRlcHRoUmFuZ2VQ",
            "cm90bxIPCgdxdWFsaXR5GAggASgCEhYKDmlzX2xhcmdlX2ltYWdlGAkgASgI",
            "IuYCChFTY2FuTWV0YWRhdGFQcm90bxIKCgJpZBgBIAEoCRIkCgppbWFnZV9z",
            "aXplGAIgASgLMhAuUmFzdGVyU2l6ZVByb3RvEiQKCmRlcHRoX3NpemUYAyAB",
            "KAsyEC5SYXN0ZXJTaXplUHJvdG8SFwoPc3RhcnRfdGltZXN0YW1wGAQgASgB",
            "EhcKD3RpbWV6b25lX29mZnNldBgPIAEoBRIQCghhcHBfbmFtZRgFIAEoCRIV",
            "Cg1wbGF0Zm9ybV9uYW1lGAYgASgJEhIKCm1vZGVsX25hbWUYByABKAkSGQoR",
            "bWFudWZhY3R1cmVyX25hbWUYCCABKAkSCwoDcG9pGAkgASgJEhAKCHJlY29y",
            "ZGVyGAogASgJEhEKCXVzZXJfanNvbhgLIAEoCRIUCgxuYXRpdmVfZGVwdGgY",
            "DCABKAgSDgoGb3JpZ2luGA0gAygCEhcKD2dsb2JhbF9yb3RhdGlvbhgOIAMo",
            "AiJgChFDYW1lcmFQYXJhbXNQcm90bxINCgV3aWR0aBgBIAEoBRIOCgZoZWln",
            "aHQYAiABKAUSCQoBZhgDIAEoAhIKCgJweBgEIAEoAhIKCgJweRgFIAEoAhIJ",
            "CgFrGAYgASgCIj0KFEFmZmluZVRyYW5zZm9ybVByb3RvEhAKCHJvdGF0aW9u",
            "GAEgAygCEhMKC3RyYW5zbGF0aW9uGAIgAygCIsIBCg1Mb2NhdGlvblByb3Rv",
            "EhEKCXRpbWVzdGFtcBgBIAEoARIQCghsYXRpdHVkZRgCIAEoARIRCglsb25n",
            "aXR1ZGUYAyABKAESEAoIYWNjdXJhY3kYBCABKAISGAoQZWxldmF0aW9uX21l",
            "dGVycxgFIAEoAhIaChJlbGV2YXRpb25fYWNjdXJhY3kYBiABKAISFwoPaGVh",
            "ZGluZ19kZWdyZWVzGAcgASgCEhgKEGhlYWRpbmdfYWNjdXJhY3kYCCABKAIi",
            "NAoRRXhwb3N1cmVJbmZvUHJvdG8SDwoHc2h1dHRlchgBIAEoAhIOCgZvZmZz",
            "ZXQYAiABKAIiLAoPRGVwdGhSYW5nZVByb3RvEgwKBG5lYXIYASABKAISCwoD",
            "ZmFyGAIgASgCIjAKD1Jhc3RlclNpemVQcm90bxINCgV3aWR0aBgBIAEoBRIO",
            "CgZoZWlnaHQYAiABKAUiZgoQQm91bmRpbmdCb3hQcm90bxIMCgRsb194GAEg",
            "ASgCEgwKBGxvX3kYAiABKAISDAoEbG9fehgDIAEoAhIMCgRoaV94GAQgASgC",
            "EgwKBGhpX3kYBSABKAISDAoEaGlfehgGIAEoAkIbqgIYTmlhbnRpYy5BUkRL",
            "LkFSLlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.FramesProto), global::Niantic.ARDK.AR.Protobuf.FramesProto.Parser, new[]{ "Id", "Frames", "Anchors", "Locations" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.FrameProto), global::Niantic.ARDK.AR.Protobuf.FrameProto.Parser, new[]{ "Id", "Anchor", "Timestamp", "Camera", "Transform", "Exposure", "Range", "Quality", "IsLargeImage" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.ScanMetadataProto), global::Niantic.ARDK.AR.Protobuf.ScanMetadataProto.Parser, new[]{ "Id", "ImageSize", "DepthSize", "StartTimestamp", "TimezoneOffset", "AppName", "PlatformName", "ModelName", "ManufacturerName", "Poi", "Recorder", "UserJson", "NativeDepth", "Origin", "GlobalRotation" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.CameraParamsProto), global::Niantic.ARDK.AR.Protobuf.CameraParamsProto.Parser, new[]{ "Width", "Height", "F", "Px", "Py", "K" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.AffineTransformProto), global::Niantic.ARDK.AR.Protobuf.AffineTransformProto.Parser, new[]{ "Rotation", "Translation" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.LocationProto), global::Niantic.ARDK.AR.Protobuf.LocationProto.Parser, new[]{ "Timestamp", "Latitude", "Longitude", "Accuracy", "ElevationMeters", "ElevationAccuracy", "HeadingDegrees", "HeadingAccuracy" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.ExposureInfoProto), global::Niantic.ARDK.AR.Protobuf.ExposureInfoProto.Parser, new[]{ "Shutter", "Offset" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.DepthRangeProto), global::Niantic.ARDK.AR.Protobuf.DepthRangeProto.Parser, new[]{ "Near", "Far" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.RasterSizeProto), global::Niantic.ARDK.AR.Protobuf.RasterSizeProto.Parser, new[]{ "Width", "Height" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.BoundingBoxProto), global::Niantic.ARDK.AR.Protobuf.BoundingBoxProto.Parser, new[]{ "LoX", "LoY", "LoZ", "HiX", "HiY", "HiZ" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///  Frames and locations are stored separately in frames.pb:
  /// </summary>
  public sealed partial class FramesProto : pb::IMessage<FramesProto> {
    private static readonly pb::MessageParser<FramesProto> _parser = new pb::MessageParser<FramesProto>(() => new FramesProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FramesProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ScanKitPublicProtosReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FramesProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FramesProto(FramesProto other) : this() {
      id_ = other.id_;
      frames_ = other.frames_.Clone();
      anchors_ = other.anchors_.Clone();
      locations_ = other.locations_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FramesProto Clone() {
      return new FramesProto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    /// <summary>
    ///  ID of the scan
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "frames" field.</summary>
    public const int FramesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Niantic.ARDK.AR.Protobuf.FrameProto> _repeated_frames_codec
        = pb::FieldCodec.ForMessage(42, global::Niantic.ARDK.AR.Protobuf.FrameProto.Parser);
    private readonly pbc::RepeatedField<global::Niantic.ARDK.AR.Protobuf.FrameProto> frames_ = new pbc::RepeatedField<global::Niantic.ARDK.AR.Protobuf.FrameProto>();
    /// <summary>
    ///  List of frames in the scan.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Niantic.ARDK.AR.Protobuf.FrameProto> Frames {
      get { return frames_; }
    }

    /// <summary>Field number for the "anchors" field.</summary>
    public const int AnchorsFieldNumber = 13;
    private static readonly pb::FieldCodec<global::Niantic.ARDK.AR.Protobuf.AffineTransformProto> _repeated_anchors_codec
        = pb::FieldCodec.ForMessage(106, global::Niantic.ARDK.AR.Protobuf.AffineTransformProto.Parser);
    private readonly pbc::RepeatedField<global::Niantic.ARDK.AR.Protobuf.AffineTransformProto> anchors_ = new pbc::RepeatedField<global::Niantic.ARDK.AR.Protobuf.AffineTransformProto>();
    /// <summary>
    ///  List of final anchor positions in the scan (re-added v1.4.10)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Niantic.ARDK.AR.Protobuf.AffineTransformProto> Anchors {
      get { return anchors_; }
    }

    /// <summary>Field number for the "locations" field.</summary>
    public const int LocationsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Niantic.ARDK.AR.Protobuf.LocationProto> _repeated_locations_codec
        = pb::FieldCodec.ForMessage(18, global::Niantic.ARDK.AR.Protobuf.LocationProto.Parser);
    private readonly pbc::RepeatedField<global::Niantic.ARDK.AR.Protobuf.LocationProto> locations_ = new pbc::RepeatedField<global::Niantic.ARDK.AR.Protobuf.LocationProto>();
    /// <summary>
    ///  List of locations in the scan (added v1.3.0)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Niantic.ARDK.AR.Protobuf.LocationProto> Locations {
      get { return locations_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FramesProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FramesProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if(!frames_.Equals(other.frames_)) return false;
      if(!anchors_.Equals(other.anchors_)) return false;
      if(!locations_.Equals(other.locations_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      hash ^= frames_.GetHashCode();
      hash ^= anchors_.GetHashCode();
      hash ^= locations_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      locations_.WriteTo(output, _repeated_locations_codec);
      frames_.WriteTo(output, _repeated_frames_codec);
      anchors_.WriteTo(output, _repeated_anchors_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      size += frames_.CalculateSize(_repeated_frames_codec);
      size += anchors_.CalculateSize(_repeated_anchors_codec);
      size += locations_.CalculateSize(_repeated_locations_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FramesProto other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      frames_.Add(other.frames_);
      anchors_.Add(other.anchors_);
      locations_.Add(other.locations_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            locations_.AddEntriesFrom(input, _repeated_locations_codec);
            break;
          }
          case 42: {
            frames_.AddEntriesFrom(input, _repeated_frames_codec);
            break;
          }
          case 106: {
            anchors_.AddEntriesFrom(input, _repeated_anchors_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Represents a frame in the scan.
  /// </summary>
  public sealed partial class FrameProto : pb::IMessage<FrameProto> {
    private static readonly pb::MessageParser<FrameProto> _parser = new pb::MessageParser<FrameProto>(() => new FrameProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FrameProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ScanKitPublicProtosReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FrameProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FrameProto(FrameProto other) : this() {
      id_ = other.id_;
      anchor_ = other.anchor_;
      timestamp_ = other.timestamp_;
      Camera = other.camera_ != null ? other.Camera.Clone() : null;
      Transform = other.transform_ != null ? other.Transform.Clone() : null;
      Exposure = other.exposure_ != null ? other.Exposure.Clone() : null;
      Range = other.range_ != null ? other.Range.Clone() : null;
      quality_ = other.quality_;
      isLargeImage_ = other.isLargeImage_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FrameProto Clone() {
      return new FrameProto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    ///  Index of the frame in list of frames
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "anchor" field.</summary>
    public const int AnchorFieldNumber = 2;
    private int anchor_;
    /// <summary>
    ///  Index of anchor that this frame is attached to
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Anchor {
      get { return anchor_; }
      set {
        anchor_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 3;
    private double timestamp_;
    /// <summary>
    ///  Time relative to start of scan when this frame was captured
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "camera" field.</summary>
    public const int CameraFieldNumber = 4;
    private global::Niantic.ARDK.AR.Protobuf.CameraParamsProto camera_;
    /// <summary>
    ///  Camera parameters for this frame
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Niantic.ARDK.AR.Protobuf.CameraParamsProto Camera {
      get { return camera_; }
      set {
        camera_ = value;
      }
    }

    /// <summary>Field number for the "transform" field.</summary>
    public const int TransformFieldNumber = 5;
    private global::Niantic.ARDK.AR.Protobuf.AffineTransformProto transform_;
    /// <summary>
    ///  Maps camera into world space. This is the transform that ARKit uses in ARCamera and ARAnchor,
    ///  but rotated by 180 degrees about the x axis.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Niantic.ARDK.AR.Protobuf.AffineTransformProto Transform {
      get { return transform_; }
      set {
        transform_ = value;
      }
    }

    /// <summary>Field number for the "exposure" field.</summary>
    public const int ExposureFieldNumber = 6;
    private global::Niantic.ARDK.AR.Protobuf.ExposureInfoProto exposure_;
    /// <summary>
    ///  Exposure information for this frame
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Niantic.ARDK.AR.Protobuf.ExposureInfoProto Exposure {
      get { return exposure_; }
      set {
        exposure_ = value;
      }
    }

    /// <summary>Field number for the "range" field.</summary>
    public const int RangeFieldNumber = 7;
    private global::Niantic.ARDK.AR.Protobuf.DepthRangeProto range_;
    /// <summary>
    ///  Near and far depth range
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Niantic.ARDK.AR.Protobuf.DepthRangeProto Range {
      get { return range_; }
      set {
        range_ = value;
      }
    }

    /// <summary>Field number for the "quality" field.</summary>
    public const int QualityFieldNumber = 8;
    private float quality_;
    /// <summary>
    ///  Quality score for this frame, based on blurriness, depth completeness.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Quality {
      get { return quality_; }
      set {
        quality_ = value;
      }
    }

    /// <summary>Field number for the "is_large_image" field.</summary>
    public const int IsLargeImageFieldNumber = 9;
    private bool isLargeImage_;
    /// <summary>
    ///  Whether this frame has a large image for texturing
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsLargeImage {
      get { return isLargeImage_; }
      set {
        isLargeImage_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FrameProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FrameProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Anchor != other.Anchor) return false;
      if (Timestamp != other.Timestamp) return false;
      if (!object.Equals(Camera, other.Camera)) return false;
      if (!object.Equals(Transform, other.Transform)) return false;
      if (!object.Equals(Exposure, other.Exposure)) return false;
      if (!object.Equals(Range, other.Range)) return false;
      if (Quality != other.Quality) return false;
      if (IsLargeImage != other.IsLargeImage) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Anchor != 0) hash ^= Anchor.GetHashCode();
      if (Timestamp != 0D) hash ^= Timestamp.GetHashCode();
      if (camera_ != null) hash ^= Camera.GetHashCode();
      if (transform_ != null) hash ^= Transform.GetHashCode();
      if (exposure_ != null) hash ^= Exposure.GetHashCode();
      if (range_ != null) hash ^= Range.GetHashCode();
      if (Quality != 0F) hash ^= Quality.GetHashCode();
      if (IsLargeImage != false) hash ^= IsLargeImage.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Anchor != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Anchor);
      }
      if (Timestamp != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Timestamp);
      }
      if (camera_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Camera);
      }
      if (transform_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Transform);
      }
      if (exposure_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Exposure);
      }
      if (range_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Range);
      }
      if (Quality != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(Quality);
      }
      if (IsLargeImage != false) {
        output.WriteRawTag(72);
        output.WriteBool(IsLargeImage);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Anchor != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Anchor);
      }
      if (Timestamp != 0D) {
        size += 1 + 8;
      }
      if (camera_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Camera);
      }
      if (transform_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transform);
      }
      if (exposure_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Exposure);
      }
      if (range_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Range);
      }
      if (Quality != 0F) {
        size += 1 + 4;
      }
      if (IsLargeImage != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FrameProto other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Anchor != 0) {
        Anchor = other.Anchor;
      }
      if (other.Timestamp != 0D) {
        Timestamp = other.Timestamp;
      }
      if (other.camera_ != null) {
        if (camera_ == null) {
          camera_ = new global::Niantic.ARDK.AR.Protobuf.CameraParamsProto();
        }
        Camera.MergeFrom(other.Camera);
      }
      if (other.transform_ != null) {
        if (transform_ == null) {
          transform_ = new global::Niantic.ARDK.AR.Protobuf.AffineTransformProto();
        }
        Transform.MergeFrom(other.Transform);
      }
      if (other.exposure_ != null) {
        if (exposure_ == null) {
          exposure_ = new global::Niantic.ARDK.AR.Protobuf.ExposureInfoProto();
        }
        Exposure.MergeFrom(other.Exposure);
      }
      if (other.range_ != null) {
        if (range_ == null) {
          range_ = new global::Niantic.ARDK.AR.Protobuf.DepthRangeProto();
        }
        Range.MergeFrom(other.Range);
      }
      if (other.Quality != 0F) {
        Quality = other.Quality;
      }
      if (other.IsLargeImage != false) {
        IsLargeImage = other.IsLargeImage;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Anchor = input.ReadInt32();
            break;
          }
          case 25: {
            Timestamp = input.ReadDouble();
            break;
          }
          case 34: {
            if (camera_ == null) {
              camera_ = new global::Niantic.ARDK.AR.Protobuf.CameraParamsProto();
            }
            input.ReadMessage(camera_);
            break;
          }
          case 42: {
            if (transform_ == null) {
              transform_ = new global::Niantic.ARDK.AR.Protobuf.AffineTransformProto();
            }
            input.ReadMessage(transform_);
            break;
          }
          case 50: {
            if (exposure_ == null) {
              exposure_ = new global::Niantic.ARDK.AR.Protobuf.ExposureInfoProto();
            }
            input.ReadMessage(exposure_);
            break;
          }
          case 58: {
            if (range_ == null) {
              range_ = new global::Niantic.ARDK.AR.Protobuf.DepthRangeProto();
            }
            input.ReadMessage(range_);
            break;
          }
          case 69: {
            Quality = input.ReadFloat();
            break;
          }
          case 72: {
            IsLargeImage = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Contains information required for uploading for scanning framework.
  /// </summary>
  public sealed partial class ScanMetadataProto : pb::IMessage<ScanMetadataProto> {
    private static readonly pb::MessageParser<ScanMetadataProto> _parser = new pb::MessageParser<ScanMetadataProto>(() => new ScanMetadataProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ScanMetadataProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ScanKitPublicProtosReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ScanMetadataProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ScanMetadataProto(ScanMetadataProto other) : this() {
      id_ = other.id_;
      ImageSize = other.imageSize_ != null ? other.ImageSize.Clone() : null;
      DepthSize = other.depthSize_ != null ? other.DepthSize.Clone() : null;
      startTimestamp_ = other.startTimestamp_;
      timezoneOffset_ = other.timezoneOffset_;
      appName_ = other.appName_;
      platformName_ = other.platformName_;
      modelName_ = other.modelName_;
      manufacturerName_ = other.manufacturerName_;
      poi_ = other.poi_;
      recorder_ = other.recorder_;
      userJson_ = other.userJson_;
      nativeDepth_ = other.nativeDepth_;
      origin_ = other.origin_.Clone();
      globalRotation_ = other.globalRotation_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ScanMetadataProto Clone() {
      return new ScanMetadataProto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "image_size" field.</summary>
    public const int ImageSizeFieldNumber = 2;
    private global::Niantic.ARDK.AR.Protobuf.RasterSizeProto imageSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Niantic.ARDK.AR.Protobuf.RasterSizeProto ImageSize {
      get { return imageSize_; }
      set {
        imageSize_ = value;
      }
    }

    /// <summary>Field number for the "depth_size" field.</summary>
    public const int DepthSizeFieldNumber = 3;
    private global::Niantic.ARDK.AR.Protobuf.RasterSizeProto depthSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Niantic.ARDK.AR.Protobuf.RasterSizeProto DepthSize {
      get { return depthSize_; }
      set {
        depthSize_ = value;
      }
    }

    /// <summary>Field number for the "start_timestamp" field.</summary>
    public const int StartTimestampFieldNumber = 4;
    private double startTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double StartTimestamp {
      get { return startTimestamp_; }
      set {
        startTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "timezone_offset" field.</summary>
    public const int TimezoneOffsetFieldNumber = 15;
    private int timezoneOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TimezoneOffset {
      get { return timezoneOffset_; }
      set {
        timezoneOffset_ = value;
      }
    }

    /// <summary>Field number for the "app_name" field.</summary>
    public const int AppNameFieldNumber = 5;
    private string appName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AppName {
      get { return appName_; }
      set {
        appName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "platform_name" field.</summary>
    public const int PlatformNameFieldNumber = 6;
    private string platformName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PlatformName {
      get { return platformName_; }
      set {
        platformName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "model_name" field.</summary>
    public const int ModelNameFieldNumber = 7;
    private string modelName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ModelName {
      get { return modelName_; }
      set {
        modelName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "manufacturer_name" field.</summary>
    public const int ManufacturerNameFieldNumber = 8;
    private string manufacturerName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ManufacturerName {
      get { return manufacturerName_; }
      set {
        manufacturerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "poi" field.</summary>
    public const int PoiFieldNumber = 9;
    private string poi_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Poi {
      get { return poi_; }
      set {
        poi_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "recorder" field.</summary>
    public const int RecorderFieldNumber = 10;
    private string recorder_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Recorder {
      get { return recorder_; }
      set {
        recorder_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_json" field.</summary>
    public const int UserJsonFieldNumber = 11;
    private string userJson_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserJson {
      get { return userJson_; }
      set {
        userJson_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "native_depth" field.</summary>
    public const int NativeDepthFieldNumber = 12;
    private bool nativeDepth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool NativeDepth {
      get { return nativeDepth_; }
      set {
        nativeDepth_ = value;
      }
    }

    /// <summary>Field number for the "origin" field.</summary>
    public const int OriginFieldNumber = 13;
    private static readonly pb::FieldCodec<float> _repeated_origin_codec
        = pb::FieldCodec.ForFloat(106);
    private readonly pbc::RepeatedField<float> origin_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> Origin {
      get { return origin_; }
    }

    /// <summary>Field number for the "global_rotation" field.</summary>
    public const int GlobalRotationFieldNumber = 14;
    private static readonly pb::FieldCodec<float> _repeated_globalRotation_codec
        = pb::FieldCodec.ForFloat(114);
    private readonly pbc::RepeatedField<float> globalRotation_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> GlobalRotation {
      get { return globalRotation_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ScanMetadataProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ScanMetadataProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(ImageSize, other.ImageSize)) return false;
      if (!object.Equals(DepthSize, other.DepthSize)) return false;
      if (StartTimestamp != other.StartTimestamp) return false;
      if (TimezoneOffset != other.TimezoneOffset) return false;
      if (AppName != other.AppName) return false;
      if (PlatformName != other.PlatformName) return false;
      if (ModelName != other.ModelName) return false;
      if (ManufacturerName != other.ManufacturerName) return false;
      if (Poi != other.Poi) return false;
      if (Recorder != other.Recorder) return false;
      if (UserJson != other.UserJson) return false;
      if (NativeDepth != other.NativeDepth) return false;
      if(!origin_.Equals(other.origin_)) return false;
      if(!globalRotation_.Equals(other.globalRotation_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (imageSize_ != null) hash ^= ImageSize.GetHashCode();
      if (depthSize_ != null) hash ^= DepthSize.GetHashCode();
      if (StartTimestamp != 0D) hash ^= StartTimestamp.GetHashCode();
      if (TimezoneOffset != 0) hash ^= TimezoneOffset.GetHashCode();
      if (AppName.Length != 0) hash ^= AppName.GetHashCode();
      if (PlatformName.Length != 0) hash ^= PlatformName.GetHashCode();
      if (ModelName.Length != 0) hash ^= ModelName.GetHashCode();
      if (ManufacturerName.Length != 0) hash ^= ManufacturerName.GetHashCode();
      if (Poi.Length != 0) hash ^= Poi.GetHashCode();
      if (Recorder.Length != 0) hash ^= Recorder.GetHashCode();
      if (UserJson.Length != 0) hash ^= UserJson.GetHashCode();
      if (NativeDepth != false) hash ^= NativeDepth.GetHashCode();
      hash ^= origin_.GetHashCode();
      hash ^= globalRotation_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (imageSize_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ImageSize);
      }
      if (depthSize_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DepthSize);
      }
      if (StartTimestamp != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(StartTimestamp);
      }
      if (AppName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AppName);
      }
      if (PlatformName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(PlatformName);
      }
      if (ModelName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ModelName);
      }
      if (ManufacturerName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ManufacturerName);
      }
      if (Poi.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Poi);
      }
      if (Recorder.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Recorder);
      }
      if (UserJson.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(UserJson);
      }
      if (NativeDepth != false) {
        output.WriteRawTag(96);
        output.WriteBool(NativeDepth);
      }
      origin_.WriteTo(output, _repeated_origin_codec);
      globalRotation_.WriteTo(output, _repeated_globalRotation_codec);
      if (TimezoneOffset != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(TimezoneOffset);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (imageSize_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ImageSize);
      }
      if (depthSize_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DepthSize);
      }
      if (StartTimestamp != 0D) {
        size += 1 + 8;
      }
      if (TimezoneOffset != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TimezoneOffset);
      }
      if (AppName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppName);
      }
      if (PlatformName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlatformName);
      }
      if (ModelName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ModelName);
      }
      if (ManufacturerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ManufacturerName);
      }
      if (Poi.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Poi);
      }
      if (Recorder.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Recorder);
      }
      if (UserJson.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserJson);
      }
      if (NativeDepth != false) {
        size += 1 + 1;
      }
      size += origin_.CalculateSize(_repeated_origin_codec);
      size += globalRotation_.CalculateSize(_repeated_globalRotation_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ScanMetadataProto other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.imageSize_ != null) {
        if (imageSize_ == null) {
          imageSize_ = new global::Niantic.ARDK.AR.Protobuf.RasterSizeProto();
        }
        ImageSize.MergeFrom(other.ImageSize);
      }
      if (other.depthSize_ != null) {
        if (depthSize_ == null) {
          depthSize_ = new global::Niantic.ARDK.AR.Protobuf.RasterSizeProto();
        }
        DepthSize.MergeFrom(other.DepthSize);
      }
      if (other.StartTimestamp != 0D) {
        StartTimestamp = other.StartTimestamp;
      }
      if (other.TimezoneOffset != 0) {
        TimezoneOffset = other.TimezoneOffset;
      }
      if (other.AppName.Length != 0) {
        AppName = other.AppName;
      }
      if (other.PlatformName.Length != 0) {
        PlatformName = other.PlatformName;
      }
      if (other.ModelName.Length != 0) {
        ModelName = other.ModelName;
      }
      if (other.ManufacturerName.Length != 0) {
        ManufacturerName = other.ManufacturerName;
      }
      if (other.Poi.Length != 0) {
        Poi = other.Poi;
      }
      if (other.Recorder.Length != 0) {
        Recorder = other.Recorder;
      }
      if (other.UserJson.Length != 0) {
        UserJson = other.UserJson;
      }
      if (other.NativeDepth != false) {
        NativeDepth = other.NativeDepth;
      }
      origin_.Add(other.origin_);
      globalRotation_.Add(other.globalRotation_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (imageSize_ == null) {
              imageSize_ = new global::Niantic.ARDK.AR.Protobuf.RasterSizeProto();
            }
            input.ReadMessage(imageSize_);
            break;
          }
          case 26: {
            if (depthSize_ == null) {
              depthSize_ = new global::Niantic.ARDK.AR.Protobuf.RasterSizeProto();
            }
            input.ReadMessage(depthSize_);
            break;
          }
          case 33: {
            StartTimestamp = input.ReadDouble();
            break;
          }
          case 42: {
            AppName = input.ReadString();
            break;
          }
          case 50: {
            PlatformName = input.ReadString();
            break;
          }
          case 58: {
            ModelName = input.ReadString();
            break;
          }
          case 66: {
            ManufacturerName = input.ReadString();
            break;
          }
          case 74: {
            Poi = input.ReadString();
            break;
          }
          case 82: {
            Recorder = input.ReadString();
            break;
          }
          case 90: {
            UserJson = input.ReadString();
            break;
          }
          case 96: {
            NativeDepth = input.ReadBool();
            break;
          }
          case 106:
          case 109: {
            origin_.AddEntriesFrom(input, _repeated_origin_codec);
            break;
          }
          case 114:
          case 117: {
            globalRotation_.AddEntriesFrom(input, _repeated_globalRotation_codec);
            break;
          }
          case 120: {
            TimezoneOffset = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Pinhole camera model with radial distortion coefficient
  /// </summary>
  public sealed partial class CameraParamsProto : pb::IMessage<CameraParamsProto> {
    private static readonly pb::MessageParser<CameraParamsProto> _parser = new pb::MessageParser<CameraParamsProto>(() => new CameraParamsProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CameraParamsProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ScanKitPublicProtosReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CameraParamsProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CameraParamsProto(CameraParamsProto other) : this() {
      width_ = other.width_;
      height_ = other.height_;
      f_ = other.f_;
      px_ = other.px_;
      py_ = other.py_;
      k_ = other.k_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CameraParamsProto Clone() {
      return new CameraParamsProto(this);
    }

    /// <summary>Field number for the "width" field.</summary>
    public const int WidthFieldNumber = 1;
    private int width_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Width {
      get { return width_; }
      set {
        width_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 2;
    private int height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "f" field.</summary>
    public const int FFieldNumber = 3;
    private float f_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float F {
      get { return f_; }
      set {
        f_ = value;
      }
    }

    /// <summary>Field number for the "px" field.</summary>
    public const int PxFieldNumber = 4;
    private float px_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Px {
      get { return px_; }
      set {
        px_ = value;
      }
    }

    /// <summary>Field number for the "py" field.</summary>
    public const int PyFieldNumber = 5;
    private float py_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Py {
      get { return py_; }
      set {
        py_ = value;
      }
    }

    /// <summary>Field number for the "k" field.</summary>
    public const int KFieldNumber = 6;
    private float k_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float K {
      get { return k_; }
      set {
        k_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CameraParamsProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CameraParamsProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Width != other.Width) return false;
      if (Height != other.Height) return false;
      if (F != other.F) return false;
      if (Px != other.Px) return false;
      if (Py != other.Py) return false;
      if (K != other.K) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Width != 0) hash ^= Width.GetHashCode();
      if (Height != 0) hash ^= Height.GetHashCode();
      if (F != 0F) hash ^= F.GetHashCode();
      if (Px != 0F) hash ^= Px.GetHashCode();
      if (Py != 0F) hash ^= Py.GetHashCode();
      if (K != 0F) hash ^= K.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Width != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Width);
      }
      if (Height != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Height);
      }
      if (F != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(F);
      }
      if (Px != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Px);
      }
      if (Py != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Py);
      }
      if (K != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(K);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Width != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Width);
      }
      if (Height != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
      }
      if (F != 0F) {
        size += 1 + 4;
      }
      if (Px != 0F) {
        size += 1 + 4;
      }
      if (Py != 0F) {
        size += 1 + 4;
      }
      if (K != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CameraParamsProto other) {
      if (other == null) {
        return;
      }
      if (other.Width != 0) {
        Width = other.Width;
      }
      if (other.Height != 0) {
        Height = other.Height;
      }
      if (other.F != 0F) {
        F = other.F;
      }
      if (other.Px != 0F) {
        Px = other.Px;
      }
      if (other.Py != 0F) {
        Py = other.Py;
      }
      if (other.K != 0F) {
        K = other.K;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Width = input.ReadInt32();
            break;
          }
          case 16: {
            Height = input.ReadInt32();
            break;
          }
          case 29: {
            F = input.ReadFloat();
            break;
          }
          case 37: {
            Px = input.ReadFloat();
            break;
          }
          case 45: {
            Py = input.ReadFloat();
            break;
          }
          case 53: {
            K = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Rotation and translation
  /// </summary>
  public sealed partial class AffineTransformProto : pb::IMessage<AffineTransformProto> {
    private static readonly pb::MessageParser<AffineTransformProto> _parser = new pb::MessageParser<AffineTransformProto>(() => new AffineTransformProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AffineTransformProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ScanKitPublicProtosReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AffineTransformProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AffineTransformProto(AffineTransformProto other) : this() {
      rotation_ = other.rotation_.Clone();
      translation_ = other.translation_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AffineTransformProto Clone() {
      return new AffineTransformProto(this);
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 1;
    private static readonly pb::FieldCodec<float> _repeated_rotation_codec
        = pb::FieldCodec.ForFloat(10);
    private readonly pbc::RepeatedField<float> rotation_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> Rotation {
      get { return rotation_; }
    }

    /// <summary>Field number for the "translation" field.</summary>
    public const int TranslationFieldNumber = 2;
    private static readonly pb::FieldCodec<float> _repeated_translation_codec
        = pb::FieldCodec.ForFloat(18);
    private readonly pbc::RepeatedField<float> translation_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> Translation {
      get { return translation_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AffineTransformProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AffineTransformProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!rotation_.Equals(other.rotation_)) return false;
      if(!translation_.Equals(other.translation_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= rotation_.GetHashCode();
      hash ^= translation_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      rotation_.WriteTo(output, _repeated_rotation_codec);
      translation_.WriteTo(output, _repeated_translation_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += rotation_.CalculateSize(_repeated_rotation_codec);
      size += translation_.CalculateSize(_repeated_translation_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AffineTransformProto other) {
      if (other == null) {
        return;
      }
      rotation_.Add(other.rotation_);
      translation_.Add(other.translation_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 13: {
            rotation_.AddEntriesFrom(input, _repeated_rotation_codec);
            break;
          }
          case 18:
          case 21: {
            translation_.AddEntriesFrom(input, _repeated_translation_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  A location stored in the scan (added v1.3.0)
  /// </summary>
  public sealed partial class LocationProto : pb::IMessage<LocationProto> {
    private static readonly pb::MessageParser<LocationProto> _parser = new pb::MessageParser<LocationProto>(() => new LocationProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LocationProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ScanKitPublicProtosReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LocationProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LocationProto(LocationProto other) : this() {
      timestamp_ = other.timestamp_;
      latitude_ = other.latitude_;
      longitude_ = other.longitude_;
      accuracy_ = other.accuracy_;
      elevationMeters_ = other.elevationMeters_;
      elevationAccuracy_ = other.elevationAccuracy_;
      headingDegrees_ = other.headingDegrees_;
      headingAccuracy_ = other.headingAccuracy_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LocationProto Clone() {
      return new LocationProto(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private double timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 2;
    private double latitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Latitude {
      get { return latitude_; }
      set {
        latitude_ = value;
      }
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 3;
    private double longitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Longitude {
      get { return longitude_; }
      set {
        longitude_ = value;
      }
    }

    /// <summary>Field number for the "accuracy" field.</summary>
    public const int AccuracyFieldNumber = 4;
    private float accuracy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Accuracy {
      get { return accuracy_; }
      set {
        accuracy_ = value;
      }
    }

    /// <summary>Field number for the "elevation_meters" field.</summary>
    public const int ElevationMetersFieldNumber = 5;
    private float elevationMeters_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float ElevationMeters {
      get { return elevationMeters_; }
      set {
        elevationMeters_ = value;
      }
    }

    /// <summary>Field number for the "elevation_accuracy" field.</summary>
    public const int ElevationAccuracyFieldNumber = 6;
    private float elevationAccuracy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float ElevationAccuracy {
      get { return elevationAccuracy_; }
      set {
        elevationAccuracy_ = value;
      }
    }

    /// <summary>Field number for the "heading_degrees" field.</summary>
    public const int HeadingDegreesFieldNumber = 7;
    private float headingDegrees_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float HeadingDegrees {
      get { return headingDegrees_; }
      set {
        headingDegrees_ = value;
      }
    }

    /// <summary>Field number for the "heading_accuracy" field.</summary>
    public const int HeadingAccuracyFieldNumber = 8;
    private float headingAccuracy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float HeadingAccuracy {
      get { return headingAccuracy_; }
      set {
        headingAccuracy_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LocationProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LocationProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if (Latitude != other.Latitude) return false;
      if (Longitude != other.Longitude) return false;
      if (Accuracy != other.Accuracy) return false;
      if (ElevationMeters != other.ElevationMeters) return false;
      if (ElevationAccuracy != other.ElevationAccuracy) return false;
      if (HeadingDegrees != other.HeadingDegrees) return false;
      if (HeadingAccuracy != other.HeadingAccuracy) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0D) hash ^= Timestamp.GetHashCode();
      if (Latitude != 0D) hash ^= Latitude.GetHashCode();
      if (Longitude != 0D) hash ^= Longitude.GetHashCode();
      if (Accuracy != 0F) hash ^= Accuracy.GetHashCode();
      if (ElevationMeters != 0F) hash ^= ElevationMeters.GetHashCode();
      if (ElevationAccuracy != 0F) hash ^= ElevationAccuracy.GetHashCode();
      if (HeadingDegrees != 0F) hash ^= HeadingDegrees.GetHashCode();
      if (HeadingAccuracy != 0F) hash ^= HeadingAccuracy.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Timestamp);
      }
      if (Latitude != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Longitude);
      }
      if (Accuracy != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Accuracy);
      }
      if (ElevationMeters != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(ElevationMeters);
      }
      if (ElevationAccuracy != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(ElevationAccuracy);
      }
      if (HeadingDegrees != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(HeadingDegrees);
      }
      if (HeadingAccuracy != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(HeadingAccuracy);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0D) {
        size += 1 + 8;
      }
      if (Latitude != 0D) {
        size += 1 + 8;
      }
      if (Longitude != 0D) {
        size += 1 + 8;
      }
      if (Accuracy != 0F) {
        size += 1 + 4;
      }
      if (ElevationMeters != 0F) {
        size += 1 + 4;
      }
      if (ElevationAccuracy != 0F) {
        size += 1 + 4;
      }
      if (HeadingDegrees != 0F) {
        size += 1 + 4;
      }
      if (HeadingAccuracy != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LocationProto other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0D) {
        Timestamp = other.Timestamp;
      }
      if (other.Latitude != 0D) {
        Latitude = other.Latitude;
      }
      if (other.Longitude != 0D) {
        Longitude = other.Longitude;
      }
      if (other.Accuracy != 0F) {
        Accuracy = other.Accuracy;
      }
      if (other.ElevationMeters != 0F) {
        ElevationMeters = other.ElevationMeters;
      }
      if (other.ElevationAccuracy != 0F) {
        ElevationAccuracy = other.ElevationAccuracy;
      }
      if (other.HeadingDegrees != 0F) {
        HeadingDegrees = other.HeadingDegrees;
      }
      if (other.HeadingAccuracy != 0F) {
        HeadingAccuracy = other.HeadingAccuracy;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 9: {
            Timestamp = input.ReadDouble();
            break;
          }
          case 17: {
            Latitude = input.ReadDouble();
            break;
          }
          case 25: {
            Longitude = input.ReadDouble();
            break;
          }
          case 37: {
            Accuracy = input.ReadFloat();
            break;
          }
          case 45: {
            ElevationMeters = input.ReadFloat();
            break;
          }
          case 53: {
            ElevationAccuracy = input.ReadFloat();
            break;
          }
          case 61: {
            HeadingDegrees = input.ReadFloat();
            break;
          }
          case 69: {
            HeadingAccuracy = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ExposureInfoProto : pb::IMessage<ExposureInfoProto> {
    private static readonly pb::MessageParser<ExposureInfoProto> _parser = new pb::MessageParser<ExposureInfoProto>(() => new ExposureInfoProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExposureInfoProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ScanKitPublicProtosReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExposureInfoProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExposureInfoProto(ExposureInfoProto other) : this() {
      shutter_ = other.shutter_;
      offset_ = other.offset_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExposureInfoProto Clone() {
      return new ExposureInfoProto(this);
    }

    /// <summary>Field number for the "shutter" field.</summary>
    public const int ShutterFieldNumber = 1;
    private float shutter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Shutter {
      get { return shutter_; }
      set {
        shutter_ = value;
      }
    }

    /// <summary>Field number for the "offset" field.</summary>
    public const int OffsetFieldNumber = 2;
    private float offset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Offset {
      get { return offset_; }
      set {
        offset_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExposureInfoProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExposureInfoProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Shutter != other.Shutter) return false;
      if (Offset != other.Offset) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Shutter != 0F) hash ^= Shutter.GetHashCode();
      if (Offset != 0F) hash ^= Offset.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Shutter != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(Shutter);
      }
      if (Offset != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Offset);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Shutter != 0F) {
        size += 1 + 4;
      }
      if (Offset != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExposureInfoProto other) {
      if (other == null) {
        return;
      }
      if (other.Shutter != 0F) {
        Shutter = other.Shutter;
      }
      if (other.Offset != 0F) {
        Offset = other.Offset;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 13: {
            Shutter = input.ReadFloat();
            break;
          }
          case 21: {
            Offset = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class DepthRangeProto : pb::IMessage<DepthRangeProto> {
    private static readonly pb::MessageParser<DepthRangeProto> _parser = new pb::MessageParser<DepthRangeProto>(() => new DepthRangeProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DepthRangeProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ScanKitPublicProtosReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DepthRangeProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DepthRangeProto(DepthRangeProto other) : this() {
      near_ = other.near_;
      far_ = other.far_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DepthRangeProto Clone() {
      return new DepthRangeProto(this);
    }

    /// <summary>Field number for the "near" field.</summary>
    public const int NearFieldNumber = 1;
    private float near_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Near {
      get { return near_; }
      set {
        near_ = value;
      }
    }

    /// <summary>Field number for the "far" field.</summary>
    public const int FarFieldNumber = 2;
    private float far_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Far {
      get { return far_; }
      set {
        far_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DepthRangeProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DepthRangeProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Near != other.Near) return false;
      if (Far != other.Far) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Near != 0F) hash ^= Near.GetHashCode();
      if (Far != 0F) hash ^= Far.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Near != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(Near);
      }
      if (Far != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Far);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Near != 0F) {
        size += 1 + 4;
      }
      if (Far != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DepthRangeProto other) {
      if (other == null) {
        return;
      }
      if (other.Near != 0F) {
        Near = other.Near;
      }
      if (other.Far != 0F) {
        Far = other.Far;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 13: {
            Near = input.ReadFloat();
            break;
          }
          case 21: {
            Far = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RasterSizeProto : pb::IMessage<RasterSizeProto> {
    private static readonly pb::MessageParser<RasterSizeProto> _parser = new pb::MessageParser<RasterSizeProto>(() => new RasterSizeProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RasterSizeProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ScanKitPublicProtosReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RasterSizeProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RasterSizeProto(RasterSizeProto other) : this() {
      width_ = other.width_;
      height_ = other.height_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RasterSizeProto Clone() {
      return new RasterSizeProto(this);
    }

    /// <summary>Field number for the "width" field.</summary>
    public const int WidthFieldNumber = 1;
    private int width_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Width {
      get { return width_; }
      set {
        width_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 2;
    private int height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RasterSizeProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RasterSizeProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Width != other.Width) return false;
      if (Height != other.Height) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Width != 0) hash ^= Width.GetHashCode();
      if (Height != 0) hash ^= Height.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Width != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Width);
      }
      if (Height != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Height);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Width != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Width);
      }
      if (Height != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RasterSizeProto other) {
      if (other == null) {
        return;
      }
      if (other.Width != 0) {
        Width = other.Width;
      }
      if (other.Height != 0) {
        Height = other.Height;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Width = input.ReadInt32();
            break;
          }
          case 16: {
            Height = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class BoundingBoxProto : pb::IMessage<BoundingBoxProto> {
    private static readonly pb::MessageParser<BoundingBoxProto> _parser = new pb::MessageParser<BoundingBoxProto>(() => new BoundingBoxProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BoundingBoxProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ScanKitPublicProtosReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BoundingBoxProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BoundingBoxProto(BoundingBoxProto other) : this() {
      loX_ = other.loX_;
      loY_ = other.loY_;
      loZ_ = other.loZ_;
      hiX_ = other.hiX_;
      hiY_ = other.hiY_;
      hiZ_ = other.hiZ_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BoundingBoxProto Clone() {
      return new BoundingBoxProto(this);
    }

    /// <summary>Field number for the "lo_x" field.</summary>
    public const int LoXFieldNumber = 1;
    private float loX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float LoX {
      get { return loX_; }
      set {
        loX_ = value;
      }
    }

    /// <summary>Field number for the "lo_y" field.</summary>
    public const int LoYFieldNumber = 2;
    private float loY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float LoY {
      get { return loY_; }
      set {
        loY_ = value;
      }
    }

    /// <summary>Field number for the "lo_z" field.</summary>
    public const int LoZFieldNumber = 3;
    private float loZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float LoZ {
      get { return loZ_; }
      set {
        loZ_ = value;
      }
    }

    /// <summary>Field number for the "hi_x" field.</summary>
    public const int HiXFieldNumber = 4;
    private float hiX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float HiX {
      get { return hiX_; }
      set {
        hiX_ = value;
      }
    }

    /// <summary>Field number for the "hi_y" field.</summary>
    public const int HiYFieldNumber = 5;
    private float hiY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float HiY {
      get { return hiY_; }
      set {
        hiY_ = value;
      }
    }

    /// <summary>Field number for the "hi_z" field.</summary>
    public const int HiZFieldNumber = 6;
    private float hiZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float HiZ {
      get { return hiZ_; }
      set {
        hiZ_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BoundingBoxProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BoundingBoxProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoX != other.LoX) return false;
      if (LoY != other.LoY) return false;
      if (LoZ != other.LoZ) return false;
      if (HiX != other.HiX) return false;
      if (HiY != other.HiY) return false;
      if (HiZ != other.HiZ) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoX != 0F) hash ^= LoX.GetHashCode();
      if (LoY != 0F) hash ^= LoY.GetHashCode();
      if (LoZ != 0F) hash ^= LoZ.GetHashCode();
      if (HiX != 0F) hash ^= HiX.GetHashCode();
      if (HiY != 0F) hash ^= HiY.GetHashCode();
      if (HiZ != 0F) hash ^= HiZ.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoX != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(LoX);
      }
      if (LoY != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(LoY);
      }
      if (LoZ != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(LoZ);
      }
      if (HiX != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(HiX);
      }
      if (HiY != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(HiY);
      }
      if (HiZ != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(HiZ);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoX != 0F) {
        size += 1 + 4;
      }
      if (LoY != 0F) {
        size += 1 + 4;
      }
      if (LoZ != 0F) {
        size += 1 + 4;
      }
      if (HiX != 0F) {
        size += 1 + 4;
      }
      if (HiY != 0F) {
        size += 1 + 4;
      }
      if (HiZ != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BoundingBoxProto other) {
      if (other == null) {
        return;
      }
      if (other.LoX != 0F) {
        LoX = other.LoX;
      }
      if (other.LoY != 0F) {
        LoY = other.LoY;
      }
      if (other.LoZ != 0F) {
        LoZ = other.LoZ;
      }
      if (other.HiX != 0F) {
        HiX = other.HiX;
      }
      if (other.HiY != 0F) {
        HiY = other.HiY;
      }
      if (other.HiZ != 0F) {
        HiZ = other.HiZ;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 13: {
            LoX = input.ReadFloat();
            break;
          }
          case 21: {
            LoY = input.ReadFloat();
            break;
          }
          case 29: {
            LoZ = input.ReadFloat();
            break;
          }
          case 37: {
            HiX = input.ReadFloat();
            break;
          }
          case 45: {
            HiY = input.ReadFloat();
            break;
          }
          case 53: {
            HiZ = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
